package sourceinfo_test

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/jhump/protoreflect/v2/internal/resolvertest"
	"github.com/jhump/protoreflect/v2/internal/testprotos"
	"github.com/jhump/protoreflect/v2/protoresolve"
	"github.com/jhump/protoreflect/v2/sourceinfo"
)

func TestFilesAndTypes(t *testing.T) {
	t.Parallel()
	// The types are backed by protoregistry.GlobalTypes, so errors for
	// elements of the wrong kind are not *protoresolve.ErrUnexpectedType.
	res := protoresolve.ResolverFromPools(sourceinfo.Files, sourceinfo.Types)
	resolvertest.CheckResolver(t, res, resolvertest.Corpus(),
		resolvertest.WithExtraFiles(), resolvertest.WithLenientTypeErrors())
}

func TestFilesAndTypesHaveSourceInfo(t *testing.T) {
	t.Parallel()
	// Only files generated by protoc-gen-gosrcinfo have source info. That
	// excludes google/protobuf/descriptor.proto.
	var corpus []protoreflect.FileDescriptor
	for _, file := range resolvertest.Corpus() {
		srcInfo, err := sourceinfo.ForFile(file.Path())
		require.NoError(t, err)
		if srcInfo != nil {
			corpus = append(corpus, file)
		}
	}
	require.NotEmpty(t, corpus)
	checkHasSourceInfo := func(t *testing.T, descriptor protoreflect.Descriptor) {
		t.Helper()
		assert.NotZero(t, descriptor.ParentFile().SourceLocations().Len(), "%s should have source info", descriptor.FullName())
	}
	for _, file := range corpus {
		found, err := sourceinfo.Files.FindFileByPath(file.Path())
		require.NoError(t, err)
		checkHasSourceInfo(t, found)
	}
	sourceinfo.Files.RangeFiles(func(file protoreflect.FileDescriptor) bool {
		if file.Path() == testprotos.File_desc_test1_proto.Path() {
			checkHasSourceInfo(t, file)
		}
		return true
	})
	sourceinfo.Files.RangeFilesByPackage("testprotos", func(file protoreflect.FileDescriptor) bool {
		checkHasSourceInfo(t, file)
		return true
	})
	for _, descriptor := range resolvertest.Descriptors(corpus) {
		found, err := sourceinfo.Files.FindDescriptorByName(descriptor.FullName())
		require.NoError(t, err)
		checkHasSourceInfo(t, found)
	}

	msgType, err := sourceinfo.Types.FindMessageByName("testprotos.TestMessage")
	require.NoError(t, err)
	checkHasSourceInfo(t, msgType.Descriptor())
	msgType, err = sourceinfo.Types.FindMessageByURL("type.googleapis.com/testprotos.TestMessage")
	require.NoError(t, err)
	checkHasSourceInfo(t, msgType.Descriptor())
	enumType, err := sourceinfo.Types.FindEnumByName("testprotos.SomeEnum")
	require.NoError(t, err)
	checkHasSourceInfo(t, enumType.Descriptor())
	extType, err := sourceinfo.Types.FindExtensionByName("testprotos.xtm")
	require.NoError(t, err)
	checkHasSourceInfo(t, extType.TypeDescriptor())
	extType, err = sourceinfo.Types.FindExtensionByNumber("testprotos.AnotherTestMessage", 100)
	require.NoError(t, err)
	checkHasSourceInfo(t, extType.TypeDescriptor())
	// The type descriptor's type should also be the type with source info.
	checkHasSourceInfo(t, extType.TypeDescriptor().Type().TypeDescriptor())
	sourceinfo.Types.RangeExtensionsByMessage("testprotos.AnotherTestMessage", func(extType protoreflect.ExtensionType) bool {
		checkHasSourceInfo(t, extType.TypeDescriptor())
		return true
	})
}

func TestAddSourceInfoToExtensionField(t *testing.T) {
	t.Parallel()
	// Extension descriptors from generated types also implement
	// protoreflect.ExtensionTypeDescriptor.
	field, err := sourceinfo.AddSourceInfoToField(testprotos.E_Xtm.TypeDescriptor())
	require.NoError(t, err)
	assert.NotZero(t, field.ParentFile().SourceLocations().Len())
	extTypeDesc, ok := field.(protoreflect.ExtensionTypeDescriptor)
	require.True(t, ok, "%T should implement protoreflect.ExtensionTypeDescriptor", field)
	assert.Equal(t, field, extTypeDesc.Type().TypeDescriptor())
}

func TestForFile(t *testing.T) {
	t.Parallel()
	srcInfo, err := sourceinfo.ForFile("desc_test1.proto")
	require.NoError(t, err)
	assert.NotEmpty(t, srcInfo.GetLocation())
	again, err := sourceinfo.ForFile("desc_test1.proto")
	require.NoError(t, err)
	assert.Same(t, srcInfo, again, "source info should be memoized")

	srcInfo, err = sourceinfo.ForFile("does/not/exist.proto")
	assert.NoError(t, err)
	assert.Nil(t, srcInfo)

	sourceinfo.Register("sourceinfo_test/invalid.proto", []byte("not gzipped data"))
	_, err = sourceinfo.ForFile("sourceinfo_test/invalid.proto")
	assert.Error(t, err)
}

func TestCorruptSourceInfo(t *testing.T) {
	t.Parallel()
	// A file registered like generated code, but with corrupt source info.
	const path = "sourceinfo_test/corrupt.proto"
	file, err := protoregistry.GlobalFiles.FindFileByPath(path)
	if err != nil {
		// Not registered by an earlier run of this test (e.g. with -count).
		file, err = protodesc.NewFile(&descriptorpb.FileDescriptorProto{
			Name:        proto.String(path),
			Package:     proto.String("sourceinfo_test.corrupt"),
			MessageType: []*descriptorpb.DescriptorProto{{Name: proto.String("Msg")}},
		}, nil)
		require.NoError(t, err)
		require.NoError(t, protoregistry.GlobalFiles.RegisterFile(file))
		sourceinfo.Register(path, []byte("not gzipped data"))
	}

	// Adding source info explicitly reports the error.
	_, err = sourceinfo.AddSourceInfoToFile(file)
	assert.Error(t, err)

	// But the registry returns the descriptors without source info.
	found, err := sourceinfo.Files.FindFileByPath(path)
	require.NoError(t, err)
	assert.Equal(t, file, found)
	msg, err := sourceinfo.Files.FindDescriptorByName("sourceinfo_test.corrupt.Msg")
	require.NoError(t, err)
	assert.Equal(t, file.Messages().Get(0), msg)
	var ranged bool
	sourceinfo.Files.RangeFilesByPackage("sourceinfo_test.corrupt", func(fd protoreflect.FileDescriptor) bool {
		ranged = true
		assert.Equal(t, file, fd)
		return true
	})
	assert.True(t, ranged)
}
