#!/usr/bin/env bash

# Regenerates the golden descriptor sets under internal/testdata and
# internal/featuresext.
#
# This fork of protocompile elides the upstream Makefile, so this script stands
# in for its "test-descriptors" and "ext-features-descriptors" targets. If the
# fork is ever re-synced with upstream, the steps below should be re-checked
# against https://github.com/bufbuild/protocompile/blob/main/Makefile.
#
# Unlike upstream, which pins its own version of protoc via a .protoc_version
# file, this uses the same protoc as internal/testprotos/make_protos.sh, so that
# all golden data in this repo is produced by a single version of protoc. To
# move to a new version of protoc, bump the version in
# internal/testprotos/protoc.sh and then re-run both scripts.

set -euo pipefail

# Descriptor set contents depend on the order of the files passed to protoc, and
# some of the invocations below use a glob. Force byte ordering so that the
# output doesn't vary with the ambient locale.
export LC_ALL=C

DIR="$(CDPATH= cd "$(dirname "${0}")" && pwd)"
cd "${DIR}"

PROTOC="$(../../../../internal/testprotos/protoc.sh)"

# Note: the file names recorded in a descriptor set are the arguments as given
# to protoc, so these must be invoked from the relevant directory with bare,
# unprefixed file names. Hence the sub-shells that change directory.

(
  cd internal/testdata

  "${PROTOC}" --descriptor_set_out=all.protoset --include_imports -I. *.proto

  "${PROTOC}" --descriptor_set_out=desc_test_complex.protoset --include_imports -I. \
    desc_test_complex.proto
  "${PROTOC}" --descriptor_set_out=desc_test_defaults.protoset --include_imports -I. \
    desc_test_defaults.proto
  "${PROTOC}" --descriptor_set_out=desc_test_proto3_optional.protoset --include_imports -I. \
    desc_test_proto3_optional.proto

  "${PROTOC}" --descriptor_set_out=descriptor_impl_tests.protoset --include_imports -I. \
    desc_test2.proto desc_test_complex.proto desc_test_defaults.proto \
    desc_test_proto3.proto desc_test_proto3_optional.proto

  # This is the only one that carries source info.
  "${PROTOC}" --descriptor_set_out=source_info.protoset --include_source_info -I. \
    desc_test_options.proto desc_test_comments.proto desc_test_complex.proto
)

(
  cd internal/testdata/editions

  "${PROTOC}" --descriptor_set_out=all.protoset --include_imports -I. *.proto

  "${PROTOC}" --descriptor_set_out=../descriptor_editions_impl_tests.protoset --include_imports -I. \
    all_default_features.proto features_with_overrides.proto file_default_delimited.proto
)

(
  cd internal/testdata/options

  # These deliberately do NOT include imports: they resolve
  # google/protobuf/descriptor.proto against the pruned copy in this directory,
  # which is hand-maintained and not generated by this script.
  for name in options test test_proto3 test_editions; do
    "${PROTOC}" --descriptor_set_out="${name}.protoset" -I. "${name}.proto"
  done
)

(
  cd internal/featuresext

  # These resolve against protoc's own bundled include directory.
  "${PROTOC}" --descriptor_set_out=cpp_features.protoset google/protobuf/cpp_features.proto
  "${PROTOC}" --descriptor_set_out=java_features.protoset google/protobuf/java_features.proto
)
