// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.1
// source: nopkg/desc_test_nopkg.proto

package nopkg

import (
	unsafe "unsafe"

	reflect "github.com/goccy/go-reflect"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_nopkg_desc_test_nopkg_proto protoreflect.FileDescriptor

const file_nopkg_desc_test_nopkg_proto_rawDesc = "" +
	"\n" +
	"\x1bnopkg/desc_test_nopkg.proto\x1a\x1fnopkg/desc_test_nopkg_new.protoBBZ@github.com/jhump/protoreflect/v2/internal/testprotos/nopkg;nopkgP\x00"

var file_nopkg_desc_test_nopkg_proto_goTypes = []any{}
var file_nopkg_desc_test_nopkg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nopkg_desc_test_nopkg_proto_init() }
func file_nopkg_desc_test_nopkg_proto_init() {
	if File_nopkg_desc_test_nopkg_proto != nil {
		return
	}
	file_nopkg_desc_test_nopkg_new_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nopkg_desc_test_nopkg_proto_rawDesc), len(file_nopkg_desc_test_nopkg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nopkg_desc_test_nopkg_proto_goTypes,
		DependencyIndexes: file_nopkg_desc_test_nopkg_proto_depIdxs,
	}.Build()
	File_nopkg_desc_test_nopkg_proto = out.File
	file_nopkg_desc_test_nopkg_proto_goTypes = nil
	file_nopkg_desc_test_nopkg_proto_depIdxs = nil
}
