// Code generated by protoc-gen-go. DO NOT EDIT.
// source: desc_test_proto3.proto

package testprotos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/any"
import google_protobuf2 "github.com/golang/protobuf/ptypes/duration"
import google_protobuf3 "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf4 "github.com/golang/protobuf/ptypes/struct"
import google_protobuf5 "github.com/golang/protobuf/ptypes/wrappers"
import jhump_protoreflect_desc "github.com/jhump/protoreflect/internal/testprotos/pkg"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Proto3Enum int32

const (
	Proto3Enum_UNKNOWN Proto3Enum = 0
	Proto3Enum_VALUE1  Proto3Enum = 1
	Proto3Enum_VALUE2  Proto3Enum = 2
)

var Proto3Enum_name = map[int32]string{
	0: "UNKNOWN",
	1: "VALUE1",
	2: "VALUE2",
}
var Proto3Enum_value = map[string]int32{
	"UNKNOWN": 0,
	"VALUE1":  1,
	"VALUE2":  2,
}

func (x Proto3Enum) String() string {
	return proto.EnumName(Proto3Enum_name, int32(x))
}
func (Proto3Enum) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type TestRequest struct {
	Foo   []Proto3Enum                                    `protobuf:"varint,1,rep,packed,name=foo,enum=testprotos.Proto3Enum" json:"foo,omitempty"`
	Bar   string                                          `protobuf:"bytes,2,opt,name=bar" json:"bar,omitempty"`
	Baz   *TestMessage                                    `protobuf:"bytes,3,opt,name=baz" json:"baz,omitempty"`
	Snafu *TestMessage_NestedMessage_AnotherNestedMessage `protobuf:"bytes,4,opt,name=snafu" json:"snafu,omitempty"`
}

func (m *TestRequest) Reset()                    { *m = TestRequest{} }
func (m *TestRequest) String() string            { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()               {}
func (*TestRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *TestRequest) GetFoo() []Proto3Enum {
	if m != nil {
		return m.Foo
	}
	return nil
}

func (m *TestRequest) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

func (m *TestRequest) GetBaz() *TestMessage {
	if m != nil {
		return m.Baz
	}
	return nil
}

func (m *TestRequest) GetSnafu() *TestMessage_NestedMessage_AnotherNestedMessage {
	if m != nil {
		return m.Snafu
	}
	return nil
}

type TestWellKnownTypes struct {
	StartTime *google_protobuf3.Timestamp   `protobuf:"bytes,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	Elapsed   *google_protobuf2.Duration    `protobuf:"bytes,2,opt,name=elapsed" json:"elapsed,omitempty"`
	Dbl       *google_protobuf5.DoubleValue `protobuf:"bytes,3,opt,name=dbl" json:"dbl,omitempty"`
	Flt       *google_protobuf5.FloatValue  `protobuf:"bytes,4,opt,name=flt" json:"flt,omitempty"`
	Bl        *google_protobuf5.BoolValue   `protobuf:"bytes,5,opt,name=bl" json:"bl,omitempty"`
	I32       *google_protobuf5.Int32Value  `protobuf:"bytes,6,opt,name=i32" json:"i32,omitempty"`
	I64       *google_protobuf5.Int64Value  `protobuf:"bytes,7,opt,name=i64" json:"i64,omitempty"`
	U32       *google_protobuf5.UInt32Value `protobuf:"bytes,8,opt,name=u32" json:"u32,omitempty"`
	U64       *google_protobuf5.UInt64Value `protobuf:"bytes,9,opt,name=u64" json:"u64,omitempty"`
	Str       *google_protobuf5.StringValue `protobuf:"bytes,10,opt,name=str" json:"str,omitempty"`
	Byt       *google_protobuf5.BytesValue  `protobuf:"bytes,11,opt,name=byt" json:"byt,omitempty"`
	Json      []*google_protobuf4.Value     `protobuf:"bytes,12,rep,name=json" json:"json,omitempty"`
	Extras    []*google_protobuf1.Any       `protobuf:"bytes,13,rep,name=extras" json:"extras,omitempty"`
}

func (m *TestWellKnownTypes) Reset()                    { *m = TestWellKnownTypes{} }
func (m *TestWellKnownTypes) String() string            { return proto.CompactTextString(m) }
func (*TestWellKnownTypes) ProtoMessage()               {}
func (*TestWellKnownTypes) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *TestWellKnownTypes) GetStartTime() *google_protobuf3.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TestWellKnownTypes) GetElapsed() *google_protobuf2.Duration {
	if m != nil {
		return m.Elapsed
	}
	return nil
}

func (m *TestWellKnownTypes) GetDbl() *google_protobuf5.DoubleValue {
	if m != nil {
		return m.Dbl
	}
	return nil
}

func (m *TestWellKnownTypes) GetFlt() *google_protobuf5.FloatValue {
	if m != nil {
		return m.Flt
	}
	return nil
}

func (m *TestWellKnownTypes) GetBl() *google_protobuf5.BoolValue {
	if m != nil {
		return m.Bl
	}
	return nil
}

func (m *TestWellKnownTypes) GetI32() *google_protobuf5.Int32Value {
	if m != nil {
		return m.I32
	}
	return nil
}

func (m *TestWellKnownTypes) GetI64() *google_protobuf5.Int64Value {
	if m != nil {
		return m.I64
	}
	return nil
}

func (m *TestWellKnownTypes) GetU32() *google_protobuf5.UInt32Value {
	if m != nil {
		return m.U32
	}
	return nil
}

func (m *TestWellKnownTypes) GetU64() *google_protobuf5.UInt64Value {
	if m != nil {
		return m.U64
	}
	return nil
}

func (m *TestWellKnownTypes) GetStr() *google_protobuf5.StringValue {
	if m != nil {
		return m.Str
	}
	return nil
}

func (m *TestWellKnownTypes) GetByt() *google_protobuf5.BytesValue {
	if m != nil {
		return m.Byt
	}
	return nil
}

func (m *TestWellKnownTypes) GetJson() []*google_protobuf4.Value {
	if m != nil {
		return m.Json
	}
	return nil
}

func (m *TestWellKnownTypes) GetExtras() []*google_protobuf1.Any {
	if m != nil {
		return m.Extras
	}
	return nil
}

type TestResponse struct {
	Atm *AnotherTestMessage `protobuf:"bytes,1,opt,name=atm" json:"atm,omitempty"`
}

func (m *TestResponse) Reset()                    { *m = TestResponse{} }
func (m *TestResponse) String() string            { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()               {}
func (*TestResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *TestResponse) GetAtm() *AnotherTestMessage {
	if m != nil {
		return m.Atm
	}
	return nil
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "testprotos.TestRequest")
	proto.RegisterType((*TestWellKnownTypes)(nil), "testprotos.TestWellKnownTypes")
	proto.RegisterType((*TestResponse)(nil), "testprotos.TestResponse")
	proto.RegisterEnum("testprotos.Proto3Enum", Proto3Enum_name, Proto3Enum_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TestService service

type TestServiceClient interface {
	DoSomething(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*jhump_protoreflect_desc.Bar, error)
	DoSomethingElse(ctx context.Context, opts ...grpc.CallOption) (TestService_DoSomethingElseClient, error)
	DoSomethingAgain(ctx context.Context, in *jhump_protoreflect_desc.Bar, opts ...grpc.CallOption) (TestService_DoSomethingAgainClient, error)
	DoSomethingForever(ctx context.Context, opts ...grpc.CallOption) (TestService_DoSomethingForeverClient, error)
}

type testServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestServiceClient(cc *grpc.ClientConn) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) DoSomething(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*jhump_protoreflect_desc.Bar, error) {
	out := new(jhump_protoreflect_desc.Bar)
	err := grpc.Invoke(ctx, "/testprotos.TestService/DoSomething", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) DoSomethingElse(ctx context.Context, opts ...grpc.CallOption) (TestService_DoSomethingElseClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TestService_serviceDesc.Streams[0], c.cc, "/testprotos.TestService/DoSomethingElse", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceDoSomethingElseClient{stream}
	return x, nil
}

type TestService_DoSomethingElseClient interface {
	Send(*TestMessage) error
	CloseAndRecv() (*TestResponse, error)
	grpc.ClientStream
}

type testServiceDoSomethingElseClient struct {
	grpc.ClientStream
}

func (x *testServiceDoSomethingElseClient) Send(m *TestMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServiceDoSomethingElseClient) CloseAndRecv() (*TestResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) DoSomethingAgain(ctx context.Context, in *jhump_protoreflect_desc.Bar, opts ...grpc.CallOption) (TestService_DoSomethingAgainClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TestService_serviceDesc.Streams[1], c.cc, "/testprotos.TestService/DoSomethingAgain", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceDoSomethingAgainClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestService_DoSomethingAgainClient interface {
	Recv() (*AnotherTestMessage, error)
	grpc.ClientStream
}

type testServiceDoSomethingAgainClient struct {
	grpc.ClientStream
}

func (x *testServiceDoSomethingAgainClient) Recv() (*AnotherTestMessage, error) {
	m := new(AnotherTestMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) DoSomethingForever(ctx context.Context, opts ...grpc.CallOption) (TestService_DoSomethingForeverClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TestService_serviceDesc.Streams[2], c.cc, "/testprotos.TestService/DoSomethingForever", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceDoSomethingForeverClient{stream}
	return x, nil
}

type TestService_DoSomethingForeverClient interface {
	Send(*TestRequest) error
	Recv() (*TestResponse, error)
	grpc.ClientStream
}

type testServiceDoSomethingForeverClient struct {
	grpc.ClientStream
}

func (x *testServiceDoSomethingForeverClient) Send(m *TestRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServiceDoSomethingForeverClient) Recv() (*TestResponse, error) {
	m := new(TestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TestService service

type TestServiceServer interface {
	DoSomething(context.Context, *TestRequest) (*jhump_protoreflect_desc.Bar, error)
	DoSomethingElse(TestService_DoSomethingElseServer) error
	DoSomethingAgain(*jhump_protoreflect_desc.Bar, TestService_DoSomethingAgainServer) error
	DoSomethingForever(TestService_DoSomethingForeverServer) error
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_DoSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).DoSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testprotos.TestService/DoSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).DoSomething(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_DoSomethingElse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).DoSomethingElse(&testServiceDoSomethingElseServer{stream})
}

type TestService_DoSomethingElseServer interface {
	SendAndClose(*TestResponse) error
	Recv() (*TestMessage, error)
	grpc.ServerStream
}

type testServiceDoSomethingElseServer struct {
	grpc.ServerStream
}

func (x *testServiceDoSomethingElseServer) SendAndClose(m *TestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServiceDoSomethingElseServer) Recv() (*TestMessage, error) {
	m := new(TestMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TestService_DoSomethingAgain_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(jhump_protoreflect_desc.Bar)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).DoSomethingAgain(m, &testServiceDoSomethingAgainServer{stream})
}

type TestService_DoSomethingAgainServer interface {
	Send(*AnotherTestMessage) error
	grpc.ServerStream
}

type testServiceDoSomethingAgainServer struct {
	grpc.ServerStream
}

func (x *testServiceDoSomethingAgainServer) Send(m *AnotherTestMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _TestService_DoSomethingForever_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).DoSomethingForever(&testServiceDoSomethingForeverServer{stream})
}

type TestService_DoSomethingForeverServer interface {
	Send(*TestResponse) error
	Recv() (*TestRequest, error)
	grpc.ServerStream
}

type testServiceDoSomethingForeverServer struct {
	grpc.ServerStream
}

func (x *testServiceDoSomethingForeverServer) Send(m *TestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServiceDoSomethingForeverServer) Recv() (*TestRequest, error) {
	m := new(TestRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testprotos.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoSomething",
			Handler:    _TestService_DoSomething_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DoSomethingElse",
			Handler:       _TestService_DoSomethingElse_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DoSomethingAgain",
			Handler:       _TestService_DoSomethingAgain_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DoSomethingForever",
			Handler:       _TestService_DoSomethingForever_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "desc_test_proto3.proto",
}

func init() { proto.RegisterFile("desc_test_proto3.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x95, 0xdf, 0x4e, 0xe3, 0x38,
	0x14, 0xc6, 0x37, 0x0d, 0x94, 0xc5, 0x65, 0x77, 0x2b, 0x6b, 0x05, 0xa1, 0x8b, 0xd8, 0x8a, 0xab,
	0x2e, 0xda, 0x4d, 0x69, 0x52, 0x55, 0xda, 0xb9, 0x9a, 0x56, 0x80, 0x34, 0x62, 0xa6, 0x83, 0xc2,
	0x3f, 0x69, 0x6e, 0x90, 0xd3, 0x9e, 0xa6, 0x81, 0xd4, 0xce, 0xd8, 0x27, 0x30, 0xe5, 0x01, 0xe6,
	0xa9, 0xe6, 0x7a, 0x9e, 0x6b, 0x94, 0xc4, 0x85, 0x40, 0x15, 0xe6, 0xaa, 0xb6, 0xcf, 0xcf, 0x9f,
	0xcf, 0xf9, 0xea, 0xe3, 0x90, 0xcd, 0x31, 0xa8, 0xd1, 0x35, 0x82, 0xc2, 0xeb, 0x58, 0x0a, 0x14,
	0xae, 0x9d, 0xfd, 0x50, 0x92, 0x2e, 0x65, 0x43, 0xd5, 0xd8, 0x0e, 0x84, 0x08, 0x22, 0x68, 0x67,
	0x53, 0x3f, 0x99, 0xb4, 0x19, 0x9f, 0xe7, 0x58, 0x63, 0xf7, 0x65, 0x68, 0x9c, 0x48, 0x86, 0xa1,
	0xe0, 0x3a, 0xfe, 0xf7, 0xcb, 0x38, 0x86, 0x33, 0x50, 0xc8, 0x66, 0xb1, 0x06, 0x76, 0x5e, 0x02,
	0x0a, 0x65, 0x32, 0xc2, 0x32, 0xf9, 0x7b, 0xc9, 0xe2, 0x18, 0xa4, 0xd2, 0xf1, 0xfa, 0x63, 0xf6,
	0x1d, 0xbd, 0xb2, 0x15, 0xdf, 0x06, 0xed, 0x42, 0x4d, 0xb7, 0x41, 0x1e, 0xd8, 0xfb, 0x6e, 0x90,
	0xda, 0x39, 0x28, 0xf4, 0xe0, 0x73, 0x02, 0x0a, 0x69, 0x8b, 0x98, 0x13, 0x21, 0x2c, 0xa3, 0x69,
	0xb6, 0x7e, 0x77, 0x36, 0xed, 0xa7, 0x72, 0xed, 0xd3, 0xcc, 0x87, 0x23, 0x9e, 0xcc, 0xbc, 0x14,
	0xa1, 0x75, 0x62, 0xfa, 0x4c, 0x5a, 0x95, 0xa6, 0xd1, 0x5a, 0xf7, 0xd2, 0x21, 0xfd, 0x27, 0x5d,
	0x79, 0xb0, 0xcc, 0xa6, 0xd1, 0xaa, 0x39, 0x5b, 0xc5, 0xbd, 0xe9, 0x09, 0x1f, 0x40, 0x29, 0x16,
	0x40, 0x8a, 0x3e, 0xd0, 0x53, 0xb2, 0xaa, 0x38, 0x9b, 0x24, 0xd6, 0x4a, 0x06, 0xbf, 0x29, 0x81,
	0xed, 0x21, 0x28, 0x84, 0xf1, 0x62, 0xd6, 0xe7, 0x02, 0xa7, 0x20, 0x9f, 0x2d, 0x7a, 0xb9, 0xd0,
	0xde, 0xd7, 0x55, 0x42, 0xd3, 0x9d, 0x57, 0x10, 0x45, 0x27, 0x5c, 0xdc, 0xf3, 0xf3, 0x79, 0x0c,
	0x8a, 0xfe, 0x4f, 0x88, 0x42, 0x26, 0xf1, 0x3a, 0x75, 0xd8, 0x32, 0xb2, 0xd3, 0x1a, 0x76, 0xee,
	0x9f, 0xbd, 0xf0, 0xcf, 0x3e, 0x5f, 0xd8, 0xef, 0xad, 0x67, 0x74, 0x3a, 0xa7, 0x2e, 0x59, 0x83,
	0x88, 0xc5, 0x0a, 0xc6, 0x59, 0x91, 0x35, 0x67, 0x7b, 0x69, 0xdf, 0xa1, 0xfe, 0x5b, 0xbd, 0x05,
	0x49, 0x6d, 0x62, 0x8e, 0xfd, 0x48, 0x7b, 0xb0, 0xb3, 0xbc, 0x41, 0x24, 0x7e, 0x04, 0x97, 0x2c,
	0x4a, 0xc0, 0x4b, 0x41, 0xfa, 0x1f, 0x31, 0x27, 0x11, 0x6a, 0x1b, 0xfe, 0x5a, 0xe2, 0x8f, 0x23,
	0xc1, 0x50, 0xe3, 0x93, 0x08, 0xe9, 0x3e, 0xa9, 0xf8, 0x91, 0xb5, 0x5a, 0x52, 0xc6, 0x40, 0x88,
	0x28, 0x87, 0x2b, 0xb9, 0x74, 0xe8, 0x3a, 0x56, 0xb5, 0x44, 0xfa, 0x1d, 0x47, 0xd7, 0xd1, 0xd2,
	0xa1, 0xeb, 0x64, 0x78, 0xaf, 0x6b, 0xad, 0x95, 0xe3, 0xbd, 0xee, 0x02, 0xef, 0x75, 0xd3, 0x42,
	0x13, 0xd7, 0xb1, 0x7e, 0x2d, 0x29, 0xf4, 0xa2, 0x28, 0x9f, 0xb8, 0x4e, 0xc6, 0xf7, 0xba, 0xd6,
	0xfa, 0x2b, 0xfc, 0xa3, 0x7e, 0x92, 0xeb, 0x2b, 0x94, 0x16, 0x29, 0xe1, 0xcf, 0x50, 0x86, 0x3c,
	0xd0, 0xbc, 0x42, 0x99, 0xa6, 0xef, 0xcf, 0xd1, 0xaa, 0x95, 0xa4, 0x3f, 0x98, 0x23, 0x28, 0x8d,
	0xfb, 0xf3, 0xd4, 0xc8, 0x95, 0x1b, 0x25, 0xb8, 0xb5, 0xd1, 0x34, 0x5b, 0x35, 0x67, 0x73, 0x89,
	0xcf, 0xd1, 0x8c, 0xa1, 0xff, 0x92, 0x2a, 0x7c, 0x41, 0xc9, 0x94, 0xf5, 0x5b, 0x46, 0xff, 0xb9,
	0x44, 0xf7, 0xf9, 0xdc, 0xd3, 0xcc, 0xde, 0x5b, 0xb2, 0x91, 0x37, 0x94, 0x8a, 0x05, 0x57, 0x40,
	0x0f, 0x88, 0xc9, 0x70, 0xa6, 0xaf, 0xde, 0x6e, 0xf1, 0xa2, 0xeb, 0xeb, 0xfc, 0xac, 0x39, 0x18,
	0xce, 0xf6, 0x3b, 0x84, 0x3c, 0x35, 0x1b, 0xad, 0x91, 0xb5, 0x8b, 0xe1, 0xc9, 0xf0, 0xe3, 0xd5,
	0xb0, 0xfe, 0x0b, 0x25, 0xa4, 0x7a, 0xd9, 0x7f, 0x7f, 0x71, 0xd4, 0xa9, 0x1b, 0x8f, 0x63, 0xa7,
	0x5e, 0x71, 0xbe, 0x55, 0xf2, 0x36, 0x3e, 0x03, 0x79, 0x17, 0x8e, 0x80, 0x1e, 0x92, 0xda, 0xa1,
	0x38, 0x13, 0x33, 0xc0, 0x69, 0xc8, 0x03, 0xba, 0xd4, 0x8c, 0xba, 0xdd, 0x1b, 0x3b, 0xf6, 0xcd,
	0x34, 0x59, 0xbc, 0x3a, 0x12, 0x26, 0x11, 0x8c, 0xd0, 0x4e, 0xdf, 0x09, 0x7b, 0xc0, 0x24, 0x3d,
	0x26, 0x7f, 0x14, 0x54, 0x8e, 0x22, 0x05, 0xb4, 0xac, 0xad, 0x1b, 0xd6, 0xf2, 0x11, 0xb9, 0x01,
	0x2d, 0x83, 0x7a, 0xa4, 0x5e, 0xd0, 0xe9, 0x07, 0x2c, 0xe4, 0xf4, 0xd5, 0x93, 0x1b, 0x3f, 0xf1,
	0xe9, 0xc0, 0xa0, 0x27, 0x84, 0x16, 0x34, 0x8f, 0x85, 0x84, 0x3b, 0x90, 0xe5, 0x85, 0xbe, 0x92,
	0xde, 0x81, 0x31, 0x70, 0x3f, 0x75, 0x82, 0x10, 0xa7, 0x89, 0x6f, 0x8f, 0xc4, 0xac, 0x9d, 0x25,
	0xd6, 0x2e, 0x26, 0xd6, 0x0e, 0x39, 0x82, 0xe4, 0x2c, 0x6a, 0x3f, 0xa9, 0xf8, 0xd5, 0xfc, 0xcb,
	0xf0, 0x23, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x56, 0xd4, 0x4f, 0x2c, 0x06, 0x00, 0x00,
}
