// Code generated by protoc-gen-go. DO NOT EDIT.
// source: desc_test1.proto

/*
Package testprotos is a generated protocol buffer package.

It is generated from these files:
	desc_test1.proto
	desc_test2.proto
	desc_test_defaults.proto
	desc_test_field_types.proto
	desc_test_options.proto
	desc_test_proto3.proto
	desc_test_wellknowntypes.proto

It has these top-level messages:
	TestMessage
	AnotherTestMessage
	Frobnitz
	Whatchamacallit
	Whatzit
	GroupX
	PrimitiveDefaults
	StringAndBytesDefaults
	EnumDefaults
	UnaryFields
	RepeatedFields
	RepeatedPackedFields
	MapKeyFields
	MapValFields
	ReallySimpleMessage
	TestRequest
	TestResponse
	TestWellKnownTypes
*/
package testprotos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Comment for NestedEnum
type TestMessage_NestedEnum int32

const (
	// Comment for VALUE1
	TestMessage_VALUE1 TestMessage_NestedEnum = 1
	// Comment for VALUE2
	TestMessage_VALUE2 TestMessage_NestedEnum = 2
)

var TestMessage_NestedEnum_name = map[int32]string{
	1: "VALUE1",
	2: "VALUE2",
}
var TestMessage_NestedEnum_value = map[string]int32{
	"VALUE1": 1,
	"VALUE2": 2,
}

func (x TestMessage_NestedEnum) Enum() *TestMessage_NestedEnum {
	p := new(TestMessage_NestedEnum)
	*p = x
	return p
}
func (x TestMessage_NestedEnum) String() string {
	return proto.EnumName(TestMessage_NestedEnum_name, int32(x))
}
func (x *TestMessage_NestedEnum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TestMessage_NestedEnum_value, data, "TestMessage_NestedEnum")
	if err != nil {
		return err
	}
	*x = TestMessage_NestedEnum(value)
	return nil
}
func (TestMessage_NestedEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Comment for DeeplyNestedEnum
type TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum int32

const (
	// Comment for VALUE1
	TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_VALUE1 TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum = 1
	// Comment for VALUE2
	TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_VALUE2 TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum = 2
)

var TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum_name = map[int32]string{
	1: "VALUE1",
	2: "VALUE2",
}
var TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum_value = map[string]int32{
	"VALUE1": 1,
	"VALUE2": 2,
}

func (x TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum) Enum() *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum {
	p := new(TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum)
	*p = x
	return p
}
func (x TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum) String() string {
	return proto.EnumName(TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum_name, int32(x))
}
func (x *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum_value, data, "TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum")
	if err != nil {
		return err
	}
	*x = TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum(value)
	return nil
}
func (TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0, 0, 0}
}

// Comment for TestMessage
type TestMessage struct {
	// Comment for nm
	Nm *TestMessage_NestedMessage `protobuf:"bytes,1,opt,name=nm" json:"nm,omitempty"`
	// Comment for anm
	Anm *TestMessage_NestedMessage_AnotherNestedMessage `protobuf:"bytes,2,opt,name=anm" json:"anm,omitempty"`
	// Comment for yanm
	Yanm *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage `protobuf:"bytes,3,opt,name=yanm" json:"yanm,omitempty"`
	// Comment for ne
	Ne               []TestMessage_NestedEnum `protobuf:"varint,4,rep,name=ne,enum=testprotos.TestMessage_NestedEnum" json:"ne,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *TestMessage) Reset()                    { *m = TestMessage{} }
func (m *TestMessage) String() string            { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()               {}
func (*TestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestMessage) GetNm() *TestMessage_NestedMessage {
	if m != nil {
		return m.Nm
	}
	return nil
}

func (m *TestMessage) GetAnm() *TestMessage_NestedMessage_AnotherNestedMessage {
	if m != nil {
		return m.Anm
	}
	return nil
}

func (m *TestMessage) GetYanm() *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage {
	if m != nil {
		return m.Yanm
	}
	return nil
}

func (m *TestMessage) GetNe() []TestMessage_NestedEnum {
	if m != nil {
		return m.Ne
	}
	return nil
}

// Comment for NestedMessage
type TestMessage_NestedMessage struct {
	// Comment for anm
	Anm *TestMessage_NestedMessage_AnotherNestedMessage `protobuf:"bytes,1,opt,name=anm" json:"anm,omitempty"`
	// Comment for yanm
	Yanm             *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage `protobuf:"bytes,2,opt,name=yanm" json:"yanm,omitempty"`
	XXX_unrecognized []byte                                                                  `json:"-"`
}

func (m *TestMessage_NestedMessage) Reset()                    { *m = TestMessage_NestedMessage{} }
func (m *TestMessage_NestedMessage) String() string            { return proto.CompactTextString(m) }
func (*TestMessage_NestedMessage) ProtoMessage()               {}
func (*TestMessage_NestedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *TestMessage_NestedMessage) GetAnm() *TestMessage_NestedMessage_AnotherNestedMessage {
	if m != nil {
		return m.Anm
	}
	return nil
}

func (m *TestMessage_NestedMessage) GetYanm() *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage {
	if m != nil {
		return m.Yanm
	}
	return nil
}

// Comment for AnotherNestedMessage
type TestMessage_NestedMessage_AnotherNestedMessage struct {
	// Comment for yanm
	Yanm             []*TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage `protobuf:"bytes,1,rep,name=yanm" json:"yanm,omitempty"`
	XXX_unrecognized []byte                                                                    `json:"-"`
}

func (m *TestMessage_NestedMessage_AnotherNestedMessage) Reset() {
	*m = TestMessage_NestedMessage_AnotherNestedMessage{}
}
func (m *TestMessage_NestedMessage_AnotherNestedMessage) String() string {
	return proto.CompactTextString(m)
}
func (*TestMessage_NestedMessage_AnotherNestedMessage) ProtoMessage() {}
func (*TestMessage_NestedMessage_AnotherNestedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0}
}

func (m *TestMessage_NestedMessage_AnotherNestedMessage) GetYanm() []*TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage {
	if m != nil {
		return m.Yanm
	}
	return nil
}

var E_TestMessage_NestedMessage_AnotherNestedMessage_Flags = &proto.ExtensionDesc{
	ExtendedType:  (*AnotherTestMessage)(nil),
	ExtensionType: ([]bool)(nil),
	Field:         200,
	Name:          "testprotos.TestMessage.NestedMessage.AnotherNestedMessage.flags",
	Tag:           "varint,200,rep,packed,name=flags",
	Filename:      "desc_test1.proto",
}

// Comment for YetAnotherNestedMessage
type TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage struct {
	// Comment for foo
	Foo *string `protobuf:"bytes,1,opt,name=foo" json:"foo,omitempty"`
	// Comment for bar
	Bar *int32 `protobuf:"varint,2,opt,name=bar" json:"bar,omitempty"`
	// Comment for baz
	Baz []byte `protobuf:"bytes,3,opt,name=baz" json:"baz,omitempty"`
	// Comment for dne
	Dne *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum `protobuf:"varint,4,opt,name=dne,enum=testprotos.TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum" json:"dne,omitempty"`
	// Comment for anm
	Anm *TestMessage_NestedMessage_AnotherNestedMessage `protobuf:"bytes,5,opt,name=anm" json:"anm,omitempty"`
	// Comment for nm
	Nm *TestMessage_NestedMessage `protobuf:"bytes,6,opt,name=nm" json:"nm,omitempty"`
	// Comment for tm
	Tm               *TestMessage `protobuf:"bytes,7,opt,name=tm" json:"tm,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage) Reset() {
	*m = TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage{}
}
func (m *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage) String() string {
	return proto.CompactTextString(m)
}
func (*TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage) ProtoMessage() {}
func (*TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0, 0}
}

func (m *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage) GetFoo() string {
	if m != nil && m.Foo != nil {
		return *m.Foo
	}
	return ""
}

func (m *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage) GetBar() int32 {
	if m != nil && m.Bar != nil {
		return *m.Bar
	}
	return 0
}

func (m *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage) GetBaz() []byte {
	if m != nil {
		return m.Baz
	}
	return nil
}

func (m *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage) GetDne() TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum {
	if m != nil && m.Dne != nil {
		return *m.Dne
	}
	return TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_VALUE1
}

func (m *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage) GetAnm() *TestMessage_NestedMessage_AnotherNestedMessage {
	if m != nil {
		return m.Anm
	}
	return nil
}

func (m *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage) GetNm() *TestMessage_NestedMessage {
	if m != nil {
		return m.Nm
	}
	return nil
}

func (m *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage) GetTm() *TestMessage {
	if m != nil {
		return m.Tm
	}
	return nil
}

// Comment for AnotherTestMessage
type AnotherTestMessage struct {
	// Comment for dne
	Dne *TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum `protobuf:"varint,1,opt,name=dne,enum=testprotos.TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum" json:"dne,omitempty"`
	// Comment for map_field1
	MapField1 map[int32]string `protobuf:"bytes,2,rep,name=map_field1,json=mapField1" json:"map_field1,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Comment for map_field2
	MapField2 map[int64]float32 `protobuf:"bytes,3,rep,name=map_field2,json=mapField2" json:"map_field2,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// Comment for map_field3
	MapField3 map[uint32]bool `protobuf:"bytes,4,rep,name=map_field3,json=mapField3" json:"map_field3,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Comment for map_field4
	MapField4                    map[string]*AnotherTestMessage `protobuf:"bytes,5,rep,name=map_field4,json=mapField4" json:"map_field4,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Rocknroll                    *AnotherTestMessage_RockNRoll  `protobuf:"group,6,opt,name=RockNRoll,json=rocknroll" json:"rocknroll,omitempty"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
}

func (m *AnotherTestMessage) Reset()                    { *m = AnotherTestMessage{} }
func (m *AnotherTestMessage) String() string            { return proto.CompactTextString(m) }
func (*AnotherTestMessage) ProtoMessage()               {}
func (*AnotherTestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

var extRange_AnotherTestMessage = []proto.ExtensionRange{
	{100, 200},
}

func (*AnotherTestMessage) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_AnotherTestMessage
}

func (m *AnotherTestMessage) GetDne() TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum {
	if m != nil && m.Dne != nil {
		return *m.Dne
	}
	return TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_VALUE1
}

func (m *AnotherTestMessage) GetMapField1() map[int32]string {
	if m != nil {
		return m.MapField1
	}
	return nil
}

func (m *AnotherTestMessage) GetMapField2() map[int64]float32 {
	if m != nil {
		return m.MapField2
	}
	return nil
}

func (m *AnotherTestMessage) GetMapField3() map[uint32]bool {
	if m != nil {
		return m.MapField3
	}
	return nil
}

func (m *AnotherTestMessage) GetMapField4() map[string]*AnotherTestMessage {
	if m != nil {
		return m.MapField4
	}
	return nil
}

func (m *AnotherTestMessage) GetRocknroll() *AnotherTestMessage_RockNRoll {
	if m != nil {
		return m.Rocknroll
	}
	return nil
}

// Comment for RockNRoll
type AnotherTestMessage_RockNRoll struct {
	// Comment for beatles
	Beatles *string `protobuf:"bytes,1,opt,name=beatles" json:"beatles,omitempty"`
	// Comment for stones
	Stones *string `protobuf:"bytes,2,opt,name=stones" json:"stones,omitempty"`
	// Comment for doors
	Doors            *string `protobuf:"bytes,3,opt,name=doors" json:"doors,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AnotherTestMessage_RockNRoll) Reset()                    { *m = AnotherTestMessage_RockNRoll{} }
func (m *AnotherTestMessage_RockNRoll) String() string            { return proto.CompactTextString(m) }
func (*AnotherTestMessage_RockNRoll) ProtoMessage()               {}
func (*AnotherTestMessage_RockNRoll) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 4} }

func (m *AnotherTestMessage_RockNRoll) GetBeatles() string {
	if m != nil && m.Beatles != nil {
		return *m.Beatles
	}
	return ""
}

func (m *AnotherTestMessage_RockNRoll) GetStones() string {
	if m != nil && m.Stones != nil {
		return *m.Stones
	}
	return ""
}

func (m *AnotherTestMessage_RockNRoll) GetDoors() string {
	if m != nil && m.Doors != nil {
		return *m.Doors
	}
	return ""
}

var E_Xtm = &proto.ExtensionDesc{
	ExtendedType:  (*AnotherTestMessage)(nil),
	ExtensionType: (*TestMessage)(nil),
	Field:         100,
	Name:          "testprotos.xtm",
	Tag:           "bytes,100,opt,name=xtm",
	Filename:      "desc_test1.proto",
}

var E_Xs = &proto.ExtensionDesc{
	ExtendedType:  (*AnotherTestMessage)(nil),
	ExtensionType: (*string)(nil),
	Field:         101,
	Name:          "testprotos.xs",
	Tag:           "bytes,101,opt,name=xs",
	Filename:      "desc_test1.proto",
}

var E_Xi = &proto.ExtensionDesc{
	ExtendedType:  (*AnotherTestMessage)(nil),
	ExtensionType: (*int32)(nil),
	Field:         102,
	Name:          "testprotos.xi",
	Tag:           "varint,102,opt,name=xi",
	Filename:      "desc_test1.proto",
}

var E_Xui = &proto.ExtensionDesc{
	ExtendedType:  (*AnotherTestMessage)(nil),
	ExtensionType: (*uint64)(nil),
	Field:         103,
	Name:          "testprotos.xui",
	Tag:           "varint,103,opt,name=xui",
	Filename:      "desc_test1.proto",
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "testprotos.TestMessage")
	proto.RegisterType((*TestMessage_NestedMessage)(nil), "testprotos.TestMessage.NestedMessage")
	proto.RegisterType((*TestMessage_NestedMessage_AnotherNestedMessage)(nil), "testprotos.TestMessage.NestedMessage.AnotherNestedMessage")
	proto.RegisterType((*TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage)(nil), "testprotos.TestMessage.NestedMessage.AnotherNestedMessage.YetAnotherNestedMessage")
	proto.RegisterType((*AnotherTestMessage)(nil), "testprotos.AnotherTestMessage")
	proto.RegisterType((*AnotherTestMessage_RockNRoll)(nil), "testprotos.AnotherTestMessage.RockNRoll")
	proto.RegisterEnum("testprotos.TestMessage_NestedEnum", TestMessage_NestedEnum_name, TestMessage_NestedEnum_value)
	proto.RegisterEnum("testprotos.TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum", TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum_name, TestMessage_NestedMessage_AnotherNestedMessage_YetAnotherNestedMessage_DeeplyNestedEnum_value)
	proto.RegisterExtension(E_TestMessage_NestedMessage_AnotherNestedMessage_Flags)
	proto.RegisterExtension(E_Xtm)
	proto.RegisterExtension(E_Xs)
	proto.RegisterExtension(E_Xi)
	proto.RegisterExtension(E_Xui)
}

func init() { proto.RegisterFile("desc_test1.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdf, 0x6a, 0xdb, 0x3e,
	0x14, 0xc7, 0xb1, 0x1c, 0xa7, 0xf1, 0xe9, 0xaf, 0xc5, 0x88, 0xf2, 0xab, 0xe9, 0xc5, 0x08, 0x61,
	0x63, 0xa1, 0x30, 0x67, 0x71, 0x32, 0xd8, 0xc2, 0x6e, 0x5a, 0xd6, 0xc2, 0xa0, 0xed, 0x85, 0xf6,
	0x07, 0x36, 0x06, 0xc5, 0x8d, 0x95, 0x34, 0xab, 0x2d, 0x05, 0x4b, 0x19, 0x49, 0x9f, 0x66, 0x17,
	0x7b, 0x98, 0xed, 0x1d, 0xf6, 0x26, 0xbb, 0xd8, 0x90, 0x92, 0x34, 0x76, 0x92, 0xd6, 0xed, 0x48,
	0x77, 0xa7, 0x63, 0x9f, 0xef, 0x47, 0x47, 0xe7, 0x1f, 0x38, 0x21, 0x15, 0xed, 0x53, 0x49, 0x85,
	0xac, 0x7b, 0xfd, 0x84, 0x4b, 0x8e, 0x41, 0x19, 0xfa, 0x28, 0x2a, 0xbf, 0x4a, 0xb0, 0xfe, 0x96,
	0x0a, 0x79, 0x4c, 0x85, 0x08, 0xba, 0x14, 0x3f, 0x03, 0xc4, 0x62, 0xd7, 0x28, 0x1b, 0xd5, 0x75,
	0xff, 0x91, 0x37, 0x73, 0xf4, 0x52, 0x4e, 0xde, 0x09, 0x15, 0x92, 0x86, 0x13, 0x8b, 0x20, 0x16,
	0xe3, 0x23, 0x30, 0x03, 0x16, 0xbb, 0x48, 0xeb, 0x5a, 0xb7, 0xd2, 0x79, 0x7b, 0x8c, 0xcb, 0x73,
	0x9a, 0x64, 0x61, 0x0a, 0x83, 0x3b, 0x50, 0x18, 0x29, 0x9c, 0xa9, 0x71, 0xe4, 0xef, 0x71, 0xde,
	0x07, 0x2a, 0x97, 0x5e, 0xa3, 0xf9, 0xd8, 0x07, 0xc4, 0xa8, 0x5b, 0x28, 0x9b, 0xd5, 0x4d, 0xbf,
	0x72, 0xf3, 0x2d, 0x07, 0x6c, 0x10, 0x13, 0xc4, 0xe8, 0xce, 0xb7, 0x22, 0x6c, 0x64, 0x58, 0xd3,
	0xb7, 0x1b, 0xab, 0x7d, 0x3b, 0xba, 0xdf, 0xb7, 0xef, 0xfc, 0x2c, 0xc0, 0xd6, 0xb2, 0xdf, 0x57,
	0x01, 0x18, 0x65, 0xf3, 0x5e, 0x03, 0xf8, 0x6a, 0xc2, 0xf6, 0x35, 0x1e, 0xd8, 0x01, 0xb3, 0xc3,
	0xb9, 0x4e, 0xa9, 0x4d, 0xd4, 0x51, 0x7d, 0x39, 0x0b, 0x12, 0x9d, 0x15, 0x8b, 0xa8, 0xe3, 0xf8,
	0xcb, 0xa5, 0xee, 0x91, 0xff, 0xd4, 0x97, 0x4b, 0x3c, 0x00, 0x33, 0xd4, 0xf5, 0x34, 0xaa, 0x9b,
	0x7e, 0x7b, 0xf5, 0x81, 0x7b, 0xaf, 0x28, 0xed, 0x47, 0xa3, 0x54, 0x43, 0xa8, 0xfb, 0xa6, 0xf5,
	0xb7, 0x56, 0x53, 0xff, 0xf1, 0x00, 0x16, 0xef, 0x3a, 0x80, 0x8f, 0x01, 0xc9, 0xd8, 0x5d, 0xd3,
	0xb2, 0xed, 0x6b, 0x64, 0x04, 0xc9, 0xb8, 0xb2, 0x0b, 0xce, 0xfc, 0x33, 0x30, 0x40, 0xf1, 0xfd,
	0xde, 0xd1, 0xbb, 0x83, 0xba, 0x63, 0x5c, 0x9d, 0x7d, 0x07, 0xf9, 0x2f, 0xc0, 0xea, 0x44, 0x41,
	0x57, 0xe0, 0x07, 0x69, 0xe2, 0x24, 0xf6, 0x14, 0xd8, 0xfd, 0xae, 0x9a, 0xa5, 0xb4, 0x8f, 0x1c,
	0x83, 0x8c, 0x15, 0x95, 0x87, 0x00, 0xf9, 0x17, 0x54, 0x7e, 0x17, 0x01, 0x2f, 0xe2, 0xa6, 0x85,
	0x34, 0xfe, 0x79, 0x21, 0x21, 0x0e, 0xfa, 0xa7, 0x9d, 0x1e, 0x8d, 0xc2, 0xba, 0x8b, 0x74, 0xff,
	0x3f, 0xb9, 0xf9, 0xe5, 0xde, 0x71, 0xd0, 0x3f, 0xd4, 0xfe, 0x07, 0x4c, 0x26, 0x23, 0x62, 0xc7,
	0x53, 0x3b, 0x43, 0xf3, 0x5d, 0xf3, 0x4e, 0x34, 0x7f, 0x8e, 0xe6, 0x67, 0x68, 0x0d, 0xbd, 0xb2,
	0x6e, 0x4f, 0x6b, 0xcc, 0xd1, 0x1a, 0x19, 0x5a, 0xd3, 0xb5, 0xee, 0x44, 0x6b, 0xce, 0xd1, 0x9a,
	0xf8, 0x10, 0xec, 0x84, 0xb7, 0x2f, 0x58, 0xc2, 0xa3, 0x48, 0x77, 0x2e, 0xf8, 0xd5, 0x1c, 0x18,
	0xe1, 0xed, 0x8b, 0x13, 0xc2, 0xa3, 0x88, 0xcc, 0xa4, 0x3b, 0x2f, 0x61, 0x33, 0x9b, 0x4e, 0x35,
	0xe3, 0x17, 0x74, 0xa4, 0x1b, 0xc1, 0x22, 0xea, 0x88, 0xb7, 0xc0, 0xfa, 0x12, 0x44, 0x03, 0xaa,
	0x37, 0x81, 0x4d, 0xc6, 0x46, 0x0b, 0x3d, 0x37, 0xd2, 0x6a, 0x7f, 0x41, 0x6d, 0x2e, 0x51, 0xa3,
	0x6b, 0xd4, 0x8d, 0x05, 0xf5, 0xc6, 0x12, 0x75, 0x29, 0xad, 0xfe, 0x34, 0x53, 0x37, 0x17, 0xd4,
	0xf6, 0x58, 0xdd, 0x4c, 0xab, 0xd7, 0xfd, 0x9c, 0x91, 0x4a, 0xd3, 0xdf, 0x80, 0x7d, 0x95, 0x2f,
	0xec, 0xc2, 0xda, 0x19, 0x0d, 0x64, 0x44, 0xc5, 0x04, 0x3e, 0x35, 0xf1, 0xff, 0x50, 0x14, 0x92,
	0x33, 0x2a, 0x26, 0xb9, 0x99, 0x58, 0x2a, 0xec, 0x90, 0xf3, 0x44, 0xe8, 0x55, 0x69, 0x93, 0xb1,
	0xb1, 0x6b, 0x95, 0x42, 0xe7, 0x87, 0xd1, 0x7a, 0x0d, 0xe6, 0x50, 0xc6, 0xb9, 0x03, 0x1e, 0xde,
	0xbc, 0x58, 0x14, 0xa3, 0xe5, 0x01, 0x1a, 0xe6, 0xaf, 0x0a, 0xaa, 0x83, 0x40, 0x43, 0xa1, 0xfd,
	0x7b, 0xb9, 0xfe, 0x1d, 0x5d, 0x7b, 0x34, 0xec, 0xb5, 0x9e, 0x82, 0x39, 0x1c, 0xe4, 0x0b, 0xba,
	0x65, 0xa3, 0x5a, 0x20, 0xca, 0x75, 0xbf, 0xf1, 0xb1, 0xde, 0xed, 0xc9, 0xf3, 0xc1, 0x99, 0xd7,
	0xe6, 0x71, 0xed, 0xf3, 0xf9, 0x20, 0xee, 0xd7, 0xb4, 0x30, 0xa1, 0x9d, 0x88, 0xb6, 0x65, 0xad,
	0xc7, 0x24, 0x4d, 0x58, 0x10, 0xd5, 0x66, 0xc8, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xff, 0x07,
	0xeb, 0xff, 0x30, 0x09, 0x00, 0x00,
}
