// Code generated by protoc-gen-go. DO NOT EDIT.
// source: desc_test_complex.proto

package testprotos // import "github.com/jhump/protoreflect/internal/testprotos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnumWithReservations int32

const (
	EnumWithReservations_X EnumWithReservations = 2
	EnumWithReservations_Y EnumWithReservations = 3
	EnumWithReservations_Z EnumWithReservations = 4
)

var EnumWithReservations_name = map[int32]string{
	2: "X",
	3: "Y",
	4: "Z",
}
var EnumWithReservations_value = map[string]int32{
	"X": 2,
	"Y": 3,
	"Z": 4,
}

func (x EnumWithReservations) Enum() *EnumWithReservations {
	p := new(EnumWithReservations)
	*p = x
	return p
}
func (x EnumWithReservations) String() string {
	return proto.EnumName(EnumWithReservations_name, int32(x))
}
func (x *EnumWithReservations) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EnumWithReservations_value, data, "EnumWithReservations")
	if err != nil {
		return err
	}
	*x = EnumWithReservations(value)
	return nil
}
func (EnumWithReservations) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{0}
}

type Test_Nested__NestedNested_EEE int32

const (
	Test_Nested__NestedNested_OK Test_Nested__NestedNested_EEE = 0
	Test_Nested__NestedNested_V1 Test_Nested__NestedNested_EEE = 1
	Test_Nested__NestedNested_V2 Test_Nested__NestedNested_EEE = 2
	Test_Nested__NestedNested_V3 Test_Nested__NestedNested_EEE = 3
	Test_Nested__NestedNested_V4 Test_Nested__NestedNested_EEE = 4
	Test_Nested__NestedNested_V5 Test_Nested__NestedNested_EEE = 5
	Test_Nested__NestedNested_V6 Test_Nested__NestedNested_EEE = 6
)

var Test_Nested__NestedNested_EEE_name = map[int32]string{
	0: "OK",
	1: "V1",
	2: "V2",
	3: "V3",
	4: "V4",
	5: "V5",
	6: "V6",
}
var Test_Nested__NestedNested_EEE_value = map[string]int32{
	"OK": 0,
	"V1": 1,
	"V2": 2,
	"V3": 3,
	"V4": 4,
	"V5": 5,
	"V6": 6,
}

func (x Test_Nested__NestedNested_EEE) Enum() *Test_Nested__NestedNested_EEE {
	p := new(Test_Nested__NestedNested_EEE)
	*p = x
	return p
}
func (x Test_Nested__NestedNested_EEE) String() string {
	return proto.EnumName(Test_Nested__NestedNested_EEE_name, int32(x))
}
func (x *Test_Nested__NestedNested_EEE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Test_Nested__NestedNested_EEE_value, data, "Test_Nested__NestedNested_EEE")
	if err != nil {
		return err
	}
	*x = Test_Nested__NestedNested_EEE(value)
	return nil
}
func (Test_Nested__NestedNested_EEE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{1, 1, 0, 0}
}

type Validator_Action int32

const (
	Validator_LOGIN Validator_Action = 0
	Validator_READ  Validator_Action = 1
	Validator_WRITE Validator_Action = 2
)

var Validator_Action_name = map[int32]string{
	0: "LOGIN",
	1: "READ",
	2: "WRITE",
}
var Validator_Action_value = map[string]int32{
	"LOGIN": 0,
	"READ":  1,
	"WRITE": 2,
}

func (x Validator_Action) Enum() *Validator_Action {
	p := new(Validator_Action)
	*p = x
	return p
}
func (x Validator_Action) String() string {
	return proto.EnumName(Validator_Action_name, int32(x))
}
func (x *Validator_Action) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Validator_Action_value, data, "Validator_Action")
	if err != nil {
		return err
	}
	*x = Validator_Action(value)
	return nil
}
func (Validator_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{4, 0}
}

type Simple struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id                   *uint64  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Simple) Reset()         { *m = Simple{} }
func (m *Simple) String() string { return proto.CompactTextString(m) }
func (*Simple) ProtoMessage()    {}
func (*Simple) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{0}
}
func (m *Simple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Simple.Unmarshal(m, b)
}
func (m *Simple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Simple.Marshal(b, m, deterministic)
}
func (dst *Simple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Simple.Merge(dst, src)
}
func (m *Simple) XXX_Size() int {
	return xxx_messageInfo_Simple.Size(m)
}
func (m *Simple) XXX_DiscardUnknown() {
	xxx_messageInfo_Simple.DiscardUnknown(m)
}

var xxx_messageInfo_Simple proto.InternalMessageInfo

func (m *Simple) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Simple) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type Test struct {
	Foo                          *string          `protobuf:"bytes,1,opt,name=foo,json=|foo|" json:"foo,omitempty"`
	Array                        []int32          `protobuf:"varint,2,rep,name=array" json:"array,omitempty"`
	S                            *Simple          `protobuf:"bytes,3,opt,name=s" json:"s,omitempty"`
	R                            []*Simple        `protobuf:"bytes,4,rep,name=r" json:"r,omitempty"`
	M                            map[string]int32 `protobuf:"bytes,5,rep,name=m" json:"m,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	B                            []byte           `protobuf:"bytes,6,opt,name=b,def=\\000\\001\\002\\003\\004\\005\\006\\007fubar!" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}         `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{1}
}

var extRange_Test = []proto.ExtensionRange{
	{Start: 100, End: 200},
	{Start: 300, End: 350},
	{Start: 500, End: 550},
}

func (*Test) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Test
}
func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (dst *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(dst, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo
var Default_Test_B []byte = []byte("\x00\x01\x02\x03\x04\x05\x06\afubar!")

func (m *Test) GetFoo() string {
	if m != nil && m.Foo != nil {
		return *m.Foo
	}
	return ""
}

func (m *Test) GetArray() []int32 {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *Test) GetS() *Simple {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *Test) GetR() []*Simple {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Test) GetM() map[string]int32 {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *Test) GetB() []byte {
	if m != nil && m.B != nil {
		return m.B
	}
	return append([]byte(nil), Default_Test_B...)
}

type Test_Nested struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test_Nested) Reset()         { *m = Test_Nested{} }
func (m *Test_Nested) String() string { return proto.CompactTextString(m) }
func (*Test_Nested) ProtoMessage()    {}
func (*Test_Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{1, 1}
}
func (m *Test_Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test_Nested.Unmarshal(m, b)
}
func (m *Test_Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test_Nested.Marshal(b, m, deterministic)
}
func (dst *Test_Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test_Nested.Merge(dst, src)
}
func (m *Test_Nested) XXX_Size() int {
	return xxx_messageInfo_Test_Nested.Size(m)
}
func (m *Test_Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_Test_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_Test_Nested proto.InternalMessageInfo

var E_Test_Nested_Fooblez = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         20003,
	Name:          "foo.bar.Test.Nested.fooblez",
	Tag:           "varint,20003,opt,name=fooblez",
	Filename:      "desc_test_complex.proto",
}

type Test_Nested__NestedNested struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test_Nested__NestedNested) Reset()         { *m = Test_Nested__NestedNested{} }
func (m *Test_Nested__NestedNested) String() string { return proto.CompactTextString(m) }
func (*Test_Nested__NestedNested) ProtoMessage()    {}
func (*Test_Nested__NestedNested) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{1, 1, 0}
}
func (m *Test_Nested__NestedNested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test_Nested__NestedNested.Unmarshal(m, b)
}
func (m *Test_Nested__NestedNested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test_Nested__NestedNested.Marshal(b, m, deterministic)
}
func (dst *Test_Nested__NestedNested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test_Nested__NestedNested.Merge(dst, src)
}
func (m *Test_Nested__NestedNested) XXX_Size() int {
	return xxx_messageInfo_Test_Nested__NestedNested.Size(m)
}
func (m *Test_Nested__NestedNested) XXX_DiscardUnknown() {
	xxx_messageInfo_Test_Nested__NestedNested.DiscardUnknown(m)
}

var xxx_messageInfo_Test_Nested__NestedNested proto.InternalMessageInfo

var E_Test_Nested_XNestedNested_XGarblez = &proto.ExtensionDesc{
	ExtendedType:  (*Test)(nil),
	ExtensionType: (*string)(nil),
	Field:         100,
	Name:          "foo.bar.Test.Nested._NestedNested._garblez",
	Tag:           "bytes,100,opt,name=_garblez,json=Garblez",
	Filename:      "desc_test_complex.proto",
}

type Test_Nested__NestedNested_NestedNestedNested struct {
	Test                 *Test    `protobuf:"bytes,1,opt,name=Test" json:"Test,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test_Nested__NestedNested_NestedNestedNested) Reset() {
	*m = Test_Nested__NestedNested_NestedNestedNested{}
}
func (m *Test_Nested__NestedNested_NestedNestedNested) String() string {
	return proto.CompactTextString(m)
}
func (*Test_Nested__NestedNested_NestedNestedNested) ProtoMessage() {}
func (*Test_Nested__NestedNested_NestedNestedNested) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{1, 1, 0, 0}
}
func (m *Test_Nested__NestedNested_NestedNestedNested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test_Nested__NestedNested_NestedNestedNested.Unmarshal(m, b)
}
func (m *Test_Nested__NestedNested_NestedNestedNested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test_Nested__NestedNested_NestedNestedNested.Marshal(b, m, deterministic)
}
func (dst *Test_Nested__NestedNested_NestedNestedNested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test_Nested__NestedNested_NestedNestedNested.Merge(dst, src)
}
func (m *Test_Nested__NestedNested_NestedNestedNested) XXX_Size() int {
	return xxx_messageInfo_Test_Nested__NestedNested_NestedNestedNested.Size(m)
}
func (m *Test_Nested__NestedNested_NestedNestedNested) XXX_DiscardUnknown() {
	xxx_messageInfo_Test_Nested__NestedNested_NestedNestedNested.DiscardUnknown(m)
}

var xxx_messageInfo_Test_Nested__NestedNested_NestedNestedNested proto.InternalMessageInfo

func (m *Test_Nested__NestedNested_NestedNestedNested) GetTest() *Test {
	if m != nil {
		return m.Test
	}
	return nil
}

type MessageWithReservations struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWithReservations) Reset()         { *m = MessageWithReservations{} }
func (m *MessageWithReservations) String() string { return proto.CompactTextString(m) }
func (*MessageWithReservations) ProtoMessage()    {}
func (*MessageWithReservations) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{2}
}
func (m *MessageWithReservations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithReservations.Unmarshal(m, b)
}
func (m *MessageWithReservations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithReservations.Marshal(b, m, deterministic)
}
func (dst *MessageWithReservations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithReservations.Merge(dst, src)
}
func (m *MessageWithReservations) XXX_Size() int {
	return xxx_messageInfo_MessageWithReservations.Size(m)
}
func (m *MessageWithReservations) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithReservations.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithReservations proto.InternalMessageInfo

type Another struct {
	Test                 *Test                          `protobuf:"bytes,1,opt,name=test" json:"test,omitempty"`
	Fff                  *Test_Nested__NestedNested_EEE `protobuf:"varint,2,opt,name=fff,enum=foo.bar.Test_Nested__NestedNested_EEE,def=1" json:"fff,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Another) Reset()         { *m = Another{} }
func (m *Another) String() string { return proto.CompactTextString(m) }
func (*Another) ProtoMessage()    {}
func (*Another) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{3}
}
func (m *Another) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Another.Unmarshal(m, b)
}
func (m *Another) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Another.Marshal(b, m, deterministic)
}
func (dst *Another) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Another.Merge(dst, src)
}
func (m *Another) XXX_Size() int {
	return xxx_messageInfo_Another.Size(m)
}
func (m *Another) XXX_DiscardUnknown() {
	xxx_messageInfo_Another.DiscardUnknown(m)
}

var xxx_messageInfo_Another proto.InternalMessageInfo

const Default_Another_Fff Test_Nested__NestedNested_EEE = Test_Nested__NestedNested_V1

func (m *Another) GetTest() *Test {
	if m != nil {
		return m.Test
	}
	return nil
}

func (m *Another) GetFff() Test_Nested__NestedNested_EEE {
	if m != nil && m.Fff != nil {
		return *m.Fff
	}
	return Default_Another_Fff
}

type Validator struct {
	Authenticated        *bool                   `protobuf:"varint,1,opt,name=authenticated" json:"authenticated,omitempty"`
	Permission           []*Validator_Permission `protobuf:"bytes,2,rep,name=permission" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{4}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (dst *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(dst, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetAuthenticated() bool {
	if m != nil && m.Authenticated != nil {
		return *m.Authenticated
	}
	return false
}

func (m *Validator) GetPermission() []*Validator_Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

type Validator_Permission struct {
	Action               *Validator_Action `protobuf:"varint,1,opt,name=action,enum=foo.bar.Validator_Action" json:"action,omitempty"`
	Entity               *string           `protobuf:"bytes,2,opt,name=entity" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Validator_Permission) Reset()         { *m = Validator_Permission{} }
func (m *Validator_Permission) String() string { return proto.CompactTextString(m) }
func (*Validator_Permission) ProtoMessage()    {}
func (*Validator_Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{4, 0}
}
func (m *Validator_Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator_Permission.Unmarshal(m, b)
}
func (m *Validator_Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator_Permission.Marshal(b, m, deterministic)
}
func (dst *Validator_Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator_Permission.Merge(dst, src)
}
func (m *Validator_Permission) XXX_Size() int {
	return xxx_messageInfo_Validator_Permission.Size(m)
}
func (m *Validator_Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Validator_Permission proto.InternalMessageInfo

func (m *Validator_Permission) GetAction() Validator_Action {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return Validator_LOGIN
}

func (m *Validator_Permission) GetEntity() string {
	if m != nil && m.Entity != nil {
		return *m.Entity
	}
	return ""
}

type Rule struct {
	// Types that are valid to be assigned to Rule:
	//	*Rule_String_
	//	*Rule_Repeated
	//	*Rule_Int
	Rule                 isRule_Rule `protobuf_oneof:"rule"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{5}
}
func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (dst *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(dst, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

type isRule_Rule interface {
	isRule_Rule()
}

type Rule_String_ struct {
	String_ *Rule_StringRule `protobuf:"bytes,1,opt,name=string,oneof"`
}
type Rule_Repeated struct {
	Repeated *Rule_RepeatedRule `protobuf:"bytes,2,opt,name=repeated,oneof"`
}
type Rule_Int struct {
	Int *Rule_IntRule `protobuf:"bytes,3,opt,name=int,oneof"`
}

func (*Rule_String_) isRule_Rule()  {}
func (*Rule_Repeated) isRule_Rule() {}
func (*Rule_Int) isRule_Rule()      {}

func (m *Rule) GetRule() isRule_Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func (m *Rule) GetString_() *Rule_StringRule {
	if x, ok := m.GetRule().(*Rule_String_); ok {
		return x.String_
	}
	return nil
}

func (m *Rule) GetRepeated() *Rule_RepeatedRule {
	if x, ok := m.GetRule().(*Rule_Repeated); ok {
		return x.Repeated
	}
	return nil
}

func (m *Rule) GetInt() *Rule_IntRule {
	if x, ok := m.GetRule().(*Rule_Int); ok {
		return x.Int
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Rule) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Rule_OneofMarshaler, _Rule_OneofUnmarshaler, _Rule_OneofSizer, []interface{}{
		(*Rule_String_)(nil),
		(*Rule_Repeated)(nil),
		(*Rule_Int)(nil),
	}
}

func _Rule_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Rule)
	// rule
	switch x := m.Rule.(type) {
	case *Rule_String_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.String_); err != nil {
			return err
		}
	case *Rule_Repeated:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Repeated); err != nil {
			return err
		}
	case *Rule_Int:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Int); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Rule.Rule has unexpected type %T", x)
	}
	return nil
}

func _Rule_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Rule)
	switch tag {
	case 1: // rule.string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Rule_StringRule)
		err := b.DecodeMessage(msg)
		m.Rule = &Rule_String_{msg}
		return true, err
	case 2: // rule.repeated
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Rule_RepeatedRule)
		err := b.DecodeMessage(msg)
		m.Rule = &Rule_Repeated{msg}
		return true, err
	case 3: // rule.int
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Rule_IntRule)
		err := b.DecodeMessage(msg)
		m.Rule = &Rule_Int{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Rule_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Rule)
	// rule
	switch x := m.Rule.(type) {
	case *Rule_String_:
		s := proto.Size(x.String_)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Rule_Repeated:
		s := proto.Size(x.Repeated)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Rule_Int:
		s := proto.Size(x.Int)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Rule_StringRule struct {
	Pattern              *string  `protobuf:"bytes,1,opt,name=pattern" json:"pattern,omitempty"`
	AllowEmpty           *bool    `protobuf:"varint,2,opt,name=allow_empty,json=allowEmpty" json:"allow_empty,omitempty"`
	MinLen               *int32   `protobuf:"varint,3,opt,name=min_len,json=minLen" json:"min_len,omitempty"`
	MaxLen               *int32   `protobuf:"varint,4,opt,name=max_len,json=maxLen" json:"max_len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule_StringRule) Reset()         { *m = Rule_StringRule{} }
func (m *Rule_StringRule) String() string { return proto.CompactTextString(m) }
func (*Rule_StringRule) ProtoMessage()    {}
func (*Rule_StringRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{5, 0}
}
func (m *Rule_StringRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule_StringRule.Unmarshal(m, b)
}
func (m *Rule_StringRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule_StringRule.Marshal(b, m, deterministic)
}
func (dst *Rule_StringRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule_StringRule.Merge(dst, src)
}
func (m *Rule_StringRule) XXX_Size() int {
	return xxx_messageInfo_Rule_StringRule.Size(m)
}
func (m *Rule_StringRule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule_StringRule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule_StringRule proto.InternalMessageInfo

func (m *Rule_StringRule) GetPattern() string {
	if m != nil && m.Pattern != nil {
		return *m.Pattern
	}
	return ""
}

func (m *Rule_StringRule) GetAllowEmpty() bool {
	if m != nil && m.AllowEmpty != nil {
		return *m.AllowEmpty
	}
	return false
}

func (m *Rule_StringRule) GetMinLen() int32 {
	if m != nil && m.MinLen != nil {
		return *m.MinLen
	}
	return 0
}

func (m *Rule_StringRule) GetMaxLen() int32 {
	if m != nil && m.MaxLen != nil {
		return *m.MaxLen
	}
	return 0
}

type Rule_IntRule struct {
	MinVal               *int64   `protobuf:"varint,1,opt,name=min_val,json=minVal" json:"min_val,omitempty"`
	MaxVal               *uint64  `protobuf:"varint,2,opt,name=max_val,json=maxVal" json:"max_val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule_IntRule) Reset()         { *m = Rule_IntRule{} }
func (m *Rule_IntRule) String() string { return proto.CompactTextString(m) }
func (*Rule_IntRule) ProtoMessage()    {}
func (*Rule_IntRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{5, 1}
}
func (m *Rule_IntRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule_IntRule.Unmarshal(m, b)
}
func (m *Rule_IntRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule_IntRule.Marshal(b, m, deterministic)
}
func (dst *Rule_IntRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule_IntRule.Merge(dst, src)
}
func (m *Rule_IntRule) XXX_Size() int {
	return xxx_messageInfo_Rule_IntRule.Size(m)
}
func (m *Rule_IntRule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule_IntRule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule_IntRule proto.InternalMessageInfo

func (m *Rule_IntRule) GetMinVal() int64 {
	if m != nil && m.MinVal != nil {
		return *m.MinVal
	}
	return 0
}

func (m *Rule_IntRule) GetMaxVal() uint64 {
	if m != nil && m.MaxVal != nil {
		return *m.MaxVal
	}
	return 0
}

type Rule_RepeatedRule struct {
	AllowEmpty           *bool    `protobuf:"varint,1,opt,name=allow_empty,json=allowEmpty" json:"allow_empty,omitempty"`
	MinItems             *int32   `protobuf:"varint,2,opt,name=min_items,json=minItems" json:"min_items,omitempty"`
	MaxItems             *int32   `protobuf:"varint,3,opt,name=max_items,json=maxItems" json:"max_items,omitempty"`
	Items                *Rule    `protobuf:"bytes,4,opt,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule_RepeatedRule) Reset()         { *m = Rule_RepeatedRule{} }
func (m *Rule_RepeatedRule) String() string { return proto.CompactTextString(m) }
func (*Rule_RepeatedRule) ProtoMessage()    {}
func (*Rule_RepeatedRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{5, 2}
}
func (m *Rule_RepeatedRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule_RepeatedRule.Unmarshal(m, b)
}
func (m *Rule_RepeatedRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule_RepeatedRule.Marshal(b, m, deterministic)
}
func (dst *Rule_RepeatedRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule_RepeatedRule.Merge(dst, src)
}
func (m *Rule_RepeatedRule) XXX_Size() int {
	return xxx_messageInfo_Rule_RepeatedRule.Size(m)
}
func (m *Rule_RepeatedRule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule_RepeatedRule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule_RepeatedRule proto.InternalMessageInfo

func (m *Rule_RepeatedRule) GetAllowEmpty() bool {
	if m != nil && m.AllowEmpty != nil {
		return *m.AllowEmpty
	}
	return false
}

func (m *Rule_RepeatedRule) GetMinItems() int32 {
	if m != nil && m.MinItems != nil {
		return *m.MinItems
	}
	return 0
}

func (m *Rule_RepeatedRule) GetMaxItems() int32 {
	if m != nil && m.MaxItems != nil {
		return *m.MaxItems
	}
	return 0
}

func (m *Rule_RepeatedRule) GetItems() *Rule {
	if m != nil {
		return m.Items
	}
	return nil
}

type IsAuthorizedReq struct {
	Subjects             []string `protobuf:"bytes,1,rep,name=subjects" json:"subjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthorizedReq) Reset()         { *m = IsAuthorizedReq{} }
func (m *IsAuthorizedReq) String() string { return proto.CompactTextString(m) }
func (*IsAuthorizedReq) ProtoMessage()    {}
func (*IsAuthorizedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{6}
}
func (m *IsAuthorizedReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthorizedReq.Unmarshal(m, b)
}
func (m *IsAuthorizedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthorizedReq.Marshal(b, m, deterministic)
}
func (dst *IsAuthorizedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthorizedReq.Merge(dst, src)
}
func (m *IsAuthorizedReq) XXX_Size() int {
	return xxx_messageInfo_IsAuthorizedReq.Size(m)
}
func (m *IsAuthorizedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthorizedReq.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthorizedReq proto.InternalMessageInfo

func (m *IsAuthorizedReq) GetSubjects() []string {
	if m != nil {
		return m.Subjects
	}
	return nil
}

type KeywordCollisions struct {
	Syntax               *bool    `protobuf:"varint,1,opt,name=syntax" json:"syntax,omitempty"`
	Import               *bool    `protobuf:"varint,2,opt,name=import" json:"import,omitempty"`
	Public               *bool    `protobuf:"varint,3,opt,name=public" json:"public,omitempty"`
	Weak                 *bool    `protobuf:"varint,4,opt,name=weak" json:"weak,omitempty"`
	Package              *bool    `protobuf:"varint,5,opt,name=package" json:"package,omitempty"`
	String_              *string  `protobuf:"bytes,6,opt,name=string" json:"string,omitempty"`
	Bytes                []byte   `protobuf:"bytes,7,opt,name=bytes" json:"bytes,omitempty"`
	Int32                *int32   `protobuf:"varint,8,opt,name=int32" json:"int32,omitempty"`
	Int64                *int64   `protobuf:"varint,9,opt,name=int64" json:"int64,omitempty"`
	Uint32               *uint32  `protobuf:"varint,10,opt,name=uint32" json:"uint32,omitempty"`
	Uint64               *uint64  `protobuf:"varint,11,opt,name=uint64" json:"uint64,omitempty"`
	Sint32               *int32   `protobuf:"zigzag32,12,opt,name=sint32" json:"sint32,omitempty"`
	Sint64               *int64   `protobuf:"zigzag64,13,opt,name=sint64" json:"sint64,omitempty"`
	Fixed32              *uint32  `protobuf:"fixed32,14,opt,name=fixed32" json:"fixed32,omitempty"`
	Fixed64              *uint64  `protobuf:"fixed64,15,opt,name=fixed64" json:"fixed64,omitempty"`
	Sfixed32             *int32   `protobuf:"fixed32,16,opt,name=sfixed32" json:"sfixed32,omitempty"`
	Sfixed64             *int64   `protobuf:"fixed64,17,opt,name=sfixed64" json:"sfixed64,omitempty"`
	Bool                 *bool    `protobuf:"varint,18,opt,name=bool" json:"bool,omitempty"`
	Float                *float32 `protobuf:"fixed32,19,opt,name=float" json:"float,omitempty"`
	Double               *float64 `protobuf:"fixed64,20,opt,name=double" json:"double,omitempty"`
	Optional             *bool    `protobuf:"varint,21,opt,name=optional" json:"optional,omitempty"`
	Repeated             *bool    `protobuf:"varint,22,opt,name=repeated" json:"repeated,omitempty"`
	Required             *bool    `protobuf:"varint,23,opt,name=required" json:"required,omitempty"`
	Message              *bool    `protobuf:"varint,24,opt,name=message" json:"message,omitempty"`
	Enum                 *bool    `protobuf:"varint,25,opt,name=enum" json:"enum,omitempty"`
	Service              *bool    `protobuf:"varint,26,opt,name=service" json:"service,omitempty"`
	Rpc                  *bool    `protobuf:"varint,27,opt,name=rpc" json:"rpc,omitempty"`
	Option               *bool    `protobuf:"varint,28,opt,name=option" json:"option,omitempty"`
	Extend               *bool    `protobuf:"varint,29,opt,name=extend" json:"extend,omitempty"`
	Extensions           *bool    `protobuf:"varint,30,opt,name=extensions" json:"extensions,omitempty"`
	Reserved             *bool    `protobuf:"varint,31,opt,name=reserved" json:"reserved,omitempty"`
	To                   *bool    `protobuf:"varint,32,opt,name=to" json:"to,omitempty"`
	True                 *int32   `protobuf:"varint,33,opt,name=true" json:"true,omitempty"`
	False                *int32   `protobuf:"varint,34,opt,name=false" json:"false,omitempty"`
	Default              *int32   `protobuf:"varint,35,opt,name=default" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeywordCollisions) Reset()         { *m = KeywordCollisions{} }
func (m *KeywordCollisions) String() string { return proto.CompactTextString(m) }
func (*KeywordCollisions) ProtoMessage()    {}
func (*KeywordCollisions) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{7}
}
func (m *KeywordCollisions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeywordCollisions.Unmarshal(m, b)
}
func (m *KeywordCollisions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeywordCollisions.Marshal(b, m, deterministic)
}
func (dst *KeywordCollisions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeywordCollisions.Merge(dst, src)
}
func (m *KeywordCollisions) XXX_Size() int {
	return xxx_messageInfo_KeywordCollisions.Size(m)
}
func (m *KeywordCollisions) XXX_DiscardUnknown() {
	xxx_messageInfo_KeywordCollisions.DiscardUnknown(m)
}

var xxx_messageInfo_KeywordCollisions proto.InternalMessageInfo

func (m *KeywordCollisions) GetSyntax() bool {
	if m != nil && m.Syntax != nil {
		return *m.Syntax
	}
	return false
}

func (m *KeywordCollisions) GetImport() bool {
	if m != nil && m.Import != nil {
		return *m.Import
	}
	return false
}

func (m *KeywordCollisions) GetPublic() bool {
	if m != nil && m.Public != nil {
		return *m.Public
	}
	return false
}

func (m *KeywordCollisions) GetWeak() bool {
	if m != nil && m.Weak != nil {
		return *m.Weak
	}
	return false
}

func (m *KeywordCollisions) GetPackage() bool {
	if m != nil && m.Package != nil {
		return *m.Package
	}
	return false
}

func (m *KeywordCollisions) GetString_() string {
	if m != nil && m.String_ != nil {
		return *m.String_
	}
	return ""
}

func (m *KeywordCollisions) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *KeywordCollisions) GetInt32() int32 {
	if m != nil && m.Int32 != nil {
		return *m.Int32
	}
	return 0
}

func (m *KeywordCollisions) GetInt64() int64 {
	if m != nil && m.Int64 != nil {
		return *m.Int64
	}
	return 0
}

func (m *KeywordCollisions) GetUint32() uint32 {
	if m != nil && m.Uint32 != nil {
		return *m.Uint32
	}
	return 0
}

func (m *KeywordCollisions) GetUint64() uint64 {
	if m != nil && m.Uint64 != nil {
		return *m.Uint64
	}
	return 0
}

func (m *KeywordCollisions) GetSint32() int32 {
	if m != nil && m.Sint32 != nil {
		return *m.Sint32
	}
	return 0
}

func (m *KeywordCollisions) GetSint64() int64 {
	if m != nil && m.Sint64 != nil {
		return *m.Sint64
	}
	return 0
}

func (m *KeywordCollisions) GetFixed32() uint32 {
	if m != nil && m.Fixed32 != nil {
		return *m.Fixed32
	}
	return 0
}

func (m *KeywordCollisions) GetFixed64() uint64 {
	if m != nil && m.Fixed64 != nil {
		return *m.Fixed64
	}
	return 0
}

func (m *KeywordCollisions) GetSfixed32() int32 {
	if m != nil && m.Sfixed32 != nil {
		return *m.Sfixed32
	}
	return 0
}

func (m *KeywordCollisions) GetSfixed64() int64 {
	if m != nil && m.Sfixed64 != nil {
		return *m.Sfixed64
	}
	return 0
}

func (m *KeywordCollisions) GetBool() bool {
	if m != nil && m.Bool != nil {
		return *m.Bool
	}
	return false
}

func (m *KeywordCollisions) GetFloat() float32 {
	if m != nil && m.Float != nil {
		return *m.Float
	}
	return 0
}

func (m *KeywordCollisions) GetDouble() float64 {
	if m != nil && m.Double != nil {
		return *m.Double
	}
	return 0
}

func (m *KeywordCollisions) GetOptional() bool {
	if m != nil && m.Optional != nil {
		return *m.Optional
	}
	return false
}

func (m *KeywordCollisions) GetRepeated() bool {
	if m != nil && m.Repeated != nil {
		return *m.Repeated
	}
	return false
}

func (m *KeywordCollisions) GetRequired() bool {
	if m != nil && m.Required != nil {
		return *m.Required
	}
	return false
}

func (m *KeywordCollisions) GetMessage() bool {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return false
}

func (m *KeywordCollisions) GetEnum() bool {
	if m != nil && m.Enum != nil {
		return *m.Enum
	}
	return false
}

func (m *KeywordCollisions) GetService() bool {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return false
}

func (m *KeywordCollisions) GetRpc() bool {
	if m != nil && m.Rpc != nil {
		return *m.Rpc
	}
	return false
}

func (m *KeywordCollisions) GetOption() bool {
	if m != nil && m.Option != nil {
		return *m.Option
	}
	return false
}

func (m *KeywordCollisions) GetExtend() bool {
	if m != nil && m.Extend != nil {
		return *m.Extend
	}
	return false
}

func (m *KeywordCollisions) GetExtensions() bool {
	if m != nil && m.Extensions != nil {
		return *m.Extensions
	}
	return false
}

func (m *KeywordCollisions) GetReserved() bool {
	if m != nil && m.Reserved != nil {
		return *m.Reserved
	}
	return false
}

func (m *KeywordCollisions) GetTo() bool {
	if m != nil && m.To != nil {
		return *m.To
	}
	return false
}

func (m *KeywordCollisions) GetTrue() int32 {
	if m != nil && m.True != nil {
		return *m.True
	}
	return 0
}

func (m *KeywordCollisions) GetFalse() int32 {
	if m != nil && m.False != nil {
		return *m.False
	}
	return 0
}

func (m *KeywordCollisions) GetDefault() int32 {
	if m != nil && m.Default != nil {
		return *m.Default
	}
	return 0
}

type KeywordCollisionOptions struct {
	Id                   *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeywordCollisionOptions) Reset()         { *m = KeywordCollisionOptions{} }
func (m *KeywordCollisionOptions) String() string { return proto.CompactTextString(m) }
func (*KeywordCollisionOptions) ProtoMessage()    {}
func (*KeywordCollisionOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_desc_test_complex_f784f166c2c4ebcd, []int{8}
}
func (m *KeywordCollisionOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeywordCollisionOptions.Unmarshal(m, b)
}
func (m *KeywordCollisionOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeywordCollisionOptions.Marshal(b, m, deterministic)
}
func (dst *KeywordCollisionOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeywordCollisionOptions.Merge(dst, src)
}
func (m *KeywordCollisionOptions) XXX_Size() int {
	return xxx_messageInfo_KeywordCollisionOptions.Size(m)
}
func (m *KeywordCollisionOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_KeywordCollisionOptions.DiscardUnknown(m)
}

var xxx_messageInfo_KeywordCollisionOptions proto.InternalMessageInfo

func (m *KeywordCollisionOptions) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *KeywordCollisionOptions) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_Label = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ExtensionRangeOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         20000,
	Name:          "foo.bar.label",
	Tag:           "bytes,20000,opt,name=label",
	Filename:      "desc_test_complex.proto",
}

var E_Rept = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: ([]*Test)(nil),
	Field:         20002,
	Name:          "foo.bar.rept",
	Tag:           "bytes,20002,rep,name=rept",
	Filename:      "desc_test_complex.proto",
}

var E_Eee = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Test_Nested__NestedNested_EEE)(nil),
	Field:         20010,
	Name:          "foo.bar.eee",
	Tag:           "varint,20010,opt,name=eee,enum=foo.bar.Test_Nested__NestedNested_EEE",
	Filename:      "desc_test_complex.proto",
}

var E_A = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Another)(nil),
	Field:         20020,
	Name:          "foo.bar.a",
	Tag:           "bytes,20020,opt,name=a",
	Filename:      "desc_test_complex.proto",
}

var E_Validator = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Validator)(nil),
	Field:         12345,
	Name:          "foo.bar.validator",
	Tag:           "bytes,12345,opt,name=validator",
	Filename:      "desc_test_complex.proto",
}

var E_Rules = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Rule)(nil),
	Field:         1234,
	Name:          "foo.bar.rules",
	Tag:           "bytes,1234,opt,name=rules",
	Filename:      "desc_test_complex.proto",
}

var E_Syntax = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20001,
	Name:          "foo.bar.syntax",
	Tag:           "varint,20001,opt,name=syntax",
	Filename:      "desc_test_complex.proto",
}

var E_Import = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20002,
	Name:          "foo.bar.import",
	Tag:           "varint,20002,opt,name=import",
	Filename:      "desc_test_complex.proto",
}

var E_Public = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20003,
	Name:          "foo.bar.public",
	Tag:           "varint,20003,opt,name=public",
	Filename:      "desc_test_complex.proto",
}

var E_Weak = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20004,
	Name:          "foo.bar.weak",
	Tag:           "varint,20004,opt,name=weak",
	Filename:      "desc_test_complex.proto",
}

var E_Package = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20005,
	Name:          "foo.bar.package",
	Tag:           "varint,20005,opt,name=package",
	Filename:      "desc_test_complex.proto",
}

var E_String = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         20006,
	Name:          "foo.bar.string",
	Tag:           "bytes,20006,opt,name=string",
	Filename:      "desc_test_complex.proto",
}

var E_Bytes = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: ([]byte)(nil),
	Field:         20007,
	Name:          "foo.bar.bytes",
	Tag:           "bytes,20007,opt,name=bytes",
	Filename:      "desc_test_complex.proto",
}

var E_Int32 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         20008,
	Name:          "foo.bar.int32",
	Tag:           "varint,20008,opt,name=int32",
	Filename:      "desc_test_complex.proto",
}

var E_Int64 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         20009,
	Name:          "foo.bar.int64",
	Tag:           "varint,20009,opt,name=int64",
	Filename:      "desc_test_complex.proto",
}

var E_Uint32 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*uint32)(nil),
	Field:         20010,
	Name:          "foo.bar.uint32",
	Tag:           "varint,20010,opt,name=uint32",
	Filename:      "desc_test_complex.proto",
}

var E_Uint64 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*uint64)(nil),
	Field:         20011,
	Name:          "foo.bar.uint64",
	Tag:           "varint,20011,opt,name=uint64",
	Filename:      "desc_test_complex.proto",
}

var E_Sint32 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         20012,
	Name:          "foo.bar.sint32",
	Tag:           "zigzag32,20012,opt,name=sint32",
	Filename:      "desc_test_complex.proto",
}

var E_Sint64 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         20013,
	Name:          "foo.bar.sint64",
	Tag:           "zigzag64,20013,opt,name=sint64",
	Filename:      "desc_test_complex.proto",
}

var E_Fixed32 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*uint32)(nil),
	Field:         20014,
	Name:          "foo.bar.fixed32",
	Tag:           "fixed32,20014,opt,name=fixed32",
	Filename:      "desc_test_complex.proto",
}

var E_Fixed64 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*uint64)(nil),
	Field:         20015,
	Name:          "foo.bar.fixed64",
	Tag:           "fixed64,20015,opt,name=fixed64",
	Filename:      "desc_test_complex.proto",
}

var E_Sfixed32 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         20016,
	Name:          "foo.bar.sfixed32",
	Tag:           "fixed32,20016,opt,name=sfixed32",
	Filename:      "desc_test_complex.proto",
}

var E_Sfixed64 = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         20017,
	Name:          "foo.bar.sfixed64",
	Tag:           "fixed64,20017,opt,name=sfixed64",
	Filename:      "desc_test_complex.proto",
}

var E_Bool = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20018,
	Name:          "foo.bar.bool",
	Tag:           "varint,20018,opt,name=bool",
	Filename:      "desc_test_complex.proto",
}

var E_Float = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*float32)(nil),
	Field:         20019,
	Name:          "foo.bar.float",
	Tag:           "fixed32,20019,opt,name=float",
	Filename:      "desc_test_complex.proto",
}

var E_Double = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*float64)(nil),
	Field:         20020,
	Name:          "foo.bar.double",
	Tag:           "fixed64,20020,opt,name=double",
	Filename:      "desc_test_complex.proto",
}

var E_Optional = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20021,
	Name:          "foo.bar.optional",
	Tag:           "varint,20021,opt,name=optional",
	Filename:      "desc_test_complex.proto",
}

var E_Repeated = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20022,
	Name:          "foo.bar.repeated",
	Tag:           "varint,20022,opt,name=repeated",
	Filename:      "desc_test_complex.proto",
}

var E_Required = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20023,
	Name:          "foo.bar.required",
	Tag:           "varint,20023,opt,name=required",
	Filename:      "desc_test_complex.proto",
}

var E_Message = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20024,
	Name:          "foo.bar.message",
	Tag:           "varint,20024,opt,name=message",
	Filename:      "desc_test_complex.proto",
}

var E_Enum = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20025,
	Name:          "foo.bar.enum",
	Tag:           "varint,20025,opt,name=enum",
	Filename:      "desc_test_complex.proto",
}

var E_Service = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20026,
	Name:          "foo.bar.service",
	Tag:           "varint,20026,opt,name=service",
	Filename:      "desc_test_complex.proto",
}

var E_Rpc = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20027,
	Name:          "foo.bar.rpc",
	Tag:           "varint,20027,opt,name=rpc",
	Filename:      "desc_test_complex.proto",
}

var E_Option = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20028,
	Name:          "foo.bar.option",
	Tag:           "varint,20028,opt,name=option",
	Filename:      "desc_test_complex.proto",
}

var E_Extend = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20029,
	Name:          "foo.bar.extend",
	Tag:           "varint,20029,opt,name=extend",
	Filename:      "desc_test_complex.proto",
}

var E_Extensions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20030,
	Name:          "foo.bar.extensions",
	Tag:           "varint,20030,opt,name=extensions",
	Filename:      "desc_test_complex.proto",
}

var E_Reserved = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20031,
	Name:          "foo.bar.reserved",
	Tag:           "varint,20031,opt,name=reserved",
	Filename:      "desc_test_complex.proto",
}

var E_To = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20032,
	Name:          "foo.bar.to",
	Tag:           "varint,20032,opt,name=to",
	Filename:      "desc_test_complex.proto",
}

var E_True = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         20033,
	Name:          "foo.bar.true",
	Tag:           "varint,20033,opt,name=true",
	Filename:      "desc_test_complex.proto",
}

var E_False = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         20034,
	Name:          "foo.bar.false",
	Tag:           "varint,20034,opt,name=false",
	Filename:      "desc_test_complex.proto",
}

var E_Default = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         20035,
	Name:          "foo.bar.default",
	Tag:           "varint,20035,opt,name=default",
	Filename:      "desc_test_complex.proto",
}

var E_Boom = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*KeywordCollisions)(nil),
	Field:         20036,
	Name:          "foo.bar.boom",
	Tag:           "bytes,20036,opt,name=boom",
	Filename:      "desc_test_complex.proto",
}

func init() {
	proto.RegisterType((*Simple)(nil), "foo.bar.Simple")
	proto.RegisterType((*Test)(nil), "foo.bar.Test")
	proto.RegisterMapType((map[string]int32)(nil), "foo.bar.Test.MEntry")
	proto.RegisterType((*Test_Nested)(nil), "foo.bar.Test.Nested")
	proto.RegisterType((*Test_Nested__NestedNested)(nil), "foo.bar.Test.Nested._NestedNested")
	proto.RegisterType((*Test_Nested__NestedNested_NestedNestedNested)(nil), "foo.bar.Test.Nested._NestedNested.NestedNestedNested")
	proto.RegisterType((*MessageWithReservations)(nil), "foo.bar.MessageWithReservations")
	proto.RegisterType((*Another)(nil), "foo.bar.Another")
	proto.RegisterType((*Validator)(nil), "foo.bar.Validator")
	proto.RegisterType((*Validator_Permission)(nil), "foo.bar.Validator.Permission")
	proto.RegisterType((*Rule)(nil), "foo.bar.Rule")
	proto.RegisterType((*Rule_StringRule)(nil), "foo.bar.Rule.StringRule")
	proto.RegisterType((*Rule_IntRule)(nil), "foo.bar.Rule.IntRule")
	proto.RegisterType((*Rule_RepeatedRule)(nil), "foo.bar.Rule.RepeatedRule")
	proto.RegisterType((*IsAuthorizedReq)(nil), "foo.bar.IsAuthorizedReq")
	proto.RegisterType((*KeywordCollisions)(nil), "foo.bar.KeywordCollisions")
	proto.RegisterType((*KeywordCollisionOptions)(nil), "foo.bar.KeywordCollisionOptions")
	proto.RegisterEnum("foo.bar.EnumWithReservations", EnumWithReservations_name, EnumWithReservations_value)
	proto.RegisterEnum("foo.bar.Test_Nested__NestedNested_EEE", Test_Nested__NestedNested_EEE_name, Test_Nested__NestedNested_EEE_value)
	proto.RegisterEnum("foo.bar.Validator_Action", Validator_Action_name, Validator_Action_value)
	proto.RegisterExtension(E_Test_Nested_Fooblez)
	proto.RegisterExtension(E_Test_Nested_XNestedNested_XGarblez)
	proto.RegisterExtension(E_Label)
	proto.RegisterExtension(E_Rept)
	proto.RegisterExtension(E_Eee)
	proto.RegisterExtension(E_A)
	proto.RegisterExtension(E_Validator)
	proto.RegisterExtension(E_Rules)
	proto.RegisterExtension(E_Syntax)
	proto.RegisterExtension(E_Import)
	proto.RegisterExtension(E_Public)
	proto.RegisterExtension(E_Weak)
	proto.RegisterExtension(E_Package)
	proto.RegisterExtension(E_String)
	proto.RegisterExtension(E_Bytes)
	proto.RegisterExtension(E_Int32)
	proto.RegisterExtension(E_Int64)
	proto.RegisterExtension(E_Uint32)
	proto.RegisterExtension(E_Uint64)
	proto.RegisterExtension(E_Sint32)
	proto.RegisterExtension(E_Sint64)
	proto.RegisterExtension(E_Fixed32)
	proto.RegisterExtension(E_Fixed64)
	proto.RegisterExtension(E_Sfixed32)
	proto.RegisterExtension(E_Sfixed64)
	proto.RegisterExtension(E_Bool)
	proto.RegisterExtension(E_Float)
	proto.RegisterExtension(E_Double)
	proto.RegisterExtension(E_Optional)
	proto.RegisterExtension(E_Repeated)
	proto.RegisterExtension(E_Required)
	proto.RegisterExtension(E_Message)
	proto.RegisterExtension(E_Enum)
	proto.RegisterExtension(E_Service)
	proto.RegisterExtension(E_Rpc)
	proto.RegisterExtension(E_Option)
	proto.RegisterExtension(E_Extend)
	proto.RegisterExtension(E_Extensions)
	proto.RegisterExtension(E_Reserved)
	proto.RegisterExtension(E_To)
	proto.RegisterExtension(E_True)
	proto.RegisterExtension(E_False)
	proto.RegisterExtension(E_Default)
	proto.RegisterExtension(E_Boom)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestTestServiceClient is the client API for TestTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestTestServiceClient interface {
	UserAuth(ctx context.Context, in *Test, opts ...grpc.CallOption) (*Test, error)
	Get(ctx context.Context, in *Test, opts ...grpc.CallOption) (*Test, error)
}

type testTestServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestTestServiceClient(cc *grpc.ClientConn) TestTestServiceClient {
	return &testTestServiceClient{cc}
}

func (c *testTestServiceClient) UserAuth(ctx context.Context, in *Test, opts ...grpc.CallOption) (*Test, error) {
	out := new(Test)
	err := c.cc.Invoke(ctx, "/foo.bar.TestTestService/UserAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testTestServiceClient) Get(ctx context.Context, in *Test, opts ...grpc.CallOption) (*Test, error) {
	out := new(Test)
	err := c.cc.Invoke(ctx, "/foo.bar.TestTestService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestTestServiceServer is the server API for TestTestService service.
type TestTestServiceServer interface {
	UserAuth(context.Context, *Test) (*Test, error)
	Get(context.Context, *Test) (*Test, error)
}

func RegisterTestTestServiceServer(s *grpc.Server, srv TestTestServiceServer) {
	s.RegisterService(&_TestTestService_serviceDesc, srv)
}

func _TestTestService_UserAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestTestServiceServer).UserAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/foo.bar.TestTestService/UserAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestTestServiceServer).UserAuth(ctx, req.(*Test))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestTestService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestTestServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/foo.bar.TestTestService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestTestServiceServer).Get(ctx, req.(*Test))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestTestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "foo.bar.TestTestService",
	HandlerType: (*TestTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserAuth",
			Handler:    _TestTestService_UserAuth_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TestTestService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desc_test_complex.proto",
}

func init() {
	proto.RegisterFile("desc_test_complex.proto", fileDescriptor_desc_test_complex_f784f166c2c4ebcd)
}

var fileDescriptor_desc_test_complex_f784f166c2c4ebcd = []byte{
	// 2590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x98, 0x5b, 0x6c, 0x1c, 0xd5,
	0x19, 0xc7, 0xfd, 0xcd, 0xec, 0xae, 0xe7, 0x1c, 0x3b, 0xc9, 0x70, 0x08, 0x64, 0xb2, 0x34, 0x64,
	0xb3, 0xa0, 0x68, 0xe3, 0xb6, 0x9b, 0xf5, 0xda, 0x31, 0x30, 0x01, 0x12, 0x3b, 0xb8, 0x90, 0x70,
	0x09, 0x1d, 0x68, 0xa0, 0x60, 0x6a, 0x66, 0x77, 0xcf, 0xda, 0x03, 0xb3, 0x33, 0xcb, 0xcc, 0x6c,
	0xb0, 0xd3, 0x48, 0x58, 0x45, 0x45, 0xf4, 0xa5, 0x4d, 0xa3, 0x3e, 0x44, 0x95, 0x91, 0xc0, 0xb4,
	0x05, 0x0a, 0x6d, 0x29, 0xbd, 0x01, 0xbd, 0x85, 0xd2, 0x87, 0x14, 0x09, 0x29, 0xe2, 0x89, 0xbe,
	0x00, 0xda, 0x8d, 0xaa, 0x3c, 0x46, 0xa2, 0x48, 0xa0, 0xaa, 0x4d, 0x75, 0x2e, 0x33, 0x6b, 0x27,
	0xa9, 0x86, 0xae, 0x64, 0xcf, 0x7c, 0xe7, 0xfb, 0x7e, 0xdf, 0xb9, 0x9f, 0xf3, 0xdf, 0xc5, 0x9b,
	0x1a, 0x34, 0xac, 0xcf, 0x46, 0x34, 0x8c, 0x66, 0xeb, 0x7e, 0xab, 0xed, 0xd2, 0x85, 0x72, 0x3b,
	0xf0, 0x23, 0x9f, 0x0c, 0x36, 0x7d, 0xbf, 0x5c, 0xb3, 0x83, 0x7c, 0x61, 0xce, 0xf7, 0xe7, 0x5c,
	0xba, 0x93, 0x17, 0xd7, 0x3a, 0xcd, 0x9d, 0x8c, 0x08, 0x9c, 0x76, 0xe4, 0x07, 0x22, 0xb4, 0xf8,
	0x25, 0x9c, 0xbb, 0xc7, 0x61, 0x2c, 0x21, 0x38, 0xe3, 0xd9, 0x2d, 0x6a, 0x40, 0x01, 0x4a, 0xc8,
	0xe2, 0xef, 0x64, 0x3d, 0x56, 0x9c, 0x86, 0xa1, 0x14, 0xa0, 0x94, 0xb1, 0x14, 0xa7, 0x51, 0x7c,
	0x37, 0x83, 0x33, 0xf7, 0xd2, 0x30, 0x22, 0x04, 0xab, 0x4d, 0xdf, 0x97, 0xb1, 0xd9, 0xa3, 0x4d,
	0xdf, 0x3f, 0x4a, 0x36, 0xe2, 0xac, 0x1d, 0x04, 0xf6, 0xa2, 0xa1, 0x14, 0xd4, 0x52, 0xd6, 0x12,
	0x06, 0xd9, 0x82, 0x21, 0x34, 0xd4, 0x02, 0x94, 0x86, 0xaa, 0x1b, 0xca, 0xb2, 0x5d, 0x65, 0x51,
	0xa5, 0x05, 0x21, 0x73, 0x07, 0x46, 0xa6, 0xa0, 0x5e, 0xd2, 0x1d, 0x90, 0x22, 0x86, 0x96, 0x91,
	0xe5, 0xee, 0x8d, 0x89, 0x9b, 0xb5, 0xa0, 0x7c, 0xe7, 0xb4, 0x17, 0x05, 0x8b, 0x16, 0xb4, 0xc8,
	0x38, 0x86, 0x9a, 0x91, 0x2b, 0x40, 0x69, 0xd8, 0xdc, 0x3e, 0x53, 0xa9, 0x54, 0x66, 0x2a, 0x95,
	0xd1, 0x99, 0x4a, 0xa5, 0x3a, 0x53, 0xa9, 0x8c, 0xcd, 0x54, 0x2a, 0xe3, 0x33, 0x95, 0xca, 0xae,
	0x99, 0x4a, 0x65, 0x62, 0xa6, 0x52, 0xb9, 0xae, 0xd9, 0xa9, 0xd9, 0xc1, 0x36, 0x0b, 0x6a, 0xf9,
	0x71, 0x9c, 0x13, 0x29, 0x88, 0x8e, 0xd5, 0x47, 0xe9, 0xa2, 0xec, 0x0b, 0x7b, 0x65, 0x3d, 0x39,
	0x6c, 0xbb, 0x1d, 0xca, 0x7b, 0x9e, 0xb5, 0x84, 0x61, 0x2a, 0xd7, 0x43, 0xfe, 0x39, 0x05, 0xe7,
	0xee, 0xa2, 0x61, 0x44, 0x1b, 0xf9, 0xbf, 0x03, 0x5e, 0x37, 0x2b, 0xde, 0x65, 0xc9, 0x7e, 0x4c,
	0x56, 0xdb, 0xe2, 0x3f, 0xd9, 0x26, 0x86, 0x8c, 0xe7, 0x1f, 0xaa, 0xae, 0x5b, 0xd3, 0x0b, 0x8b,
	0xbb, 0x4c, 0xfd, 0x78, 0x17, 0x0d, 0x63, 0x75, 0xde, 0xf7, 0x57, 0x72, 0x99, 0xb0, 0xed, 0xfb,
	0xc5, 0x9b, 0xb0, 0x3a, 0x3d, 0x3d, 0x4d, 0x72, 0x58, 0x39, 0x78, 0xbb, 0x3e, 0xc0, 0x9e, 0x87,
	0x46, 0x75, 0xe0, 0xcf, 0xaa, 0xae, 0xf0, 0xe7, 0x98, 0xae, 0xf2, 0xe7, 0xb8, 0x9e, 0xe1, 0xcf,
	0x5d, 0x7a, 0x96, 0x3f, 0x27, 0xf4, 0x5c, 0xb5, 0x84, 0xb5, 0xd9, 0x39, 0x3b, 0xa8, 0xb9, 0xf4,
	0x08, 0x59, 0x5b, 0xa3, 0xd1, 0xe0, 0xdd, 0x1c, 0xbc, 0x55, 0x78, 0xcd, 0x8d, 0xc7, 0xbb, 0x68,
	0x08, 0xab, 0x73, 0xac, 0x6a, 0xb5, 0xe6, 0xfb, 0x27, 0xba, 0xe8, 0x93, 0xbb, 0xaa, 0xbb, 0x31,
	0x5b, 0x42, 0x1c, 0xdf, 0x5a, 0x16, 0x6b, 0xa8, 0x1c, 0xaf, 0xa1, 0xf2, 0x9d, 0x34, 0x0c, 0xed,
	0x39, 0x7a, 0xb0, 0x1d, 0x39, 0xbe, 0x17, 0x1a, 0xcf, 0x2f, 0x03, 0x1f, 0xa5, 0x98, 0x18, 0xc9,
	0x6a, 0x0d, 0xfd, 0x6f, 0x30, 0xa2, 0x6b, 0xaf, 0x28, 0xfa, 0x87, 0x4a, 0x5e, 0xfb, 0x56, 0x17,
	0x65, 0x1e, 0xb1, 0x8f, 0x1c, 0x19, 0xd1, 0xb5, 0x7f, 0xaa, 0xfa, 0x0b, 0x99, 0x7e, 0x49, 0x71,
	0x0f, 0xde, 0x24, 0xb3, 0xdd, 0xe7, 0x44, 0xf3, 0x16, 0x0d, 0x69, 0x70, 0xd8, 0xe6, 0x69, 0x0f,
	0x64, 0xb4, 0xac, 0x3e, 0x74, 0x20, 0xa3, 0x0d, 0xeb, 0xfa, 0x81, 0x8c, 0x46, 0xf4, 0xcb, 0x0f,
	0x20, 0xed, 0xec, 0xa0, 0xbe, 0xb4, 0xb4, 0xb4, 0xa4, 0x58, 0x30, 0x69, 0xc1, 0x94, 0x05, 0xfb,
	0x8a, 0x27, 0x14, 0x3c, 0x38, 0xe9, 0xf9, 0xd1, 0x3c, 0x0d, 0xd8, 0x40, 0x47, 0xff, 0x7b, 0xa0,
	0x99, 0x8b, 0xdc, 0x88, 0xd5, 0x66, 0xb3, 0xc9, 0xa7, 0x75, 0x7d, 0x75, 0xfb, 0xda, 0x05, 0x25,
	0xa6, 0xab, 0xbc, 0x66, 0x4a, 0xcb, 0xd3, 0xd3, 0xd3, 0xa6, 0x72, 0x68, 0xd4, 0x62, 0x98, 0xf9,
	0x32, 0x1c, 0xef, 0xa2, 0x6b, 0xb0, 0x6a, 0xd7, 0xea, 0x3a, 0xe8, 0x8a, 0xae, 0xe6, 0x07, 0xf9,
	0x36, 0xd0, 0xbf, 0x59, 0x54, 0x31, 0x34, 0xd9, 0xbf, 0xb0, 0xa8, 0xea, 0xa7, 0xd4, 0xe3, 0x5d,
	0xb4, 0x15, 0xab, 0x0d, 0xda, 0xd4, 0x55, 0x5d, 0xd1, 0x21, 0xaf, 0x61, 0xb5, 0x66, 0x07, 0xfa,
	0x5b, 0x0a, 0x0b, 0x99, 0xe3, 0x71, 0xc7, 0xbb, 0x28, 0xcb, 0x43, 0x4e, 0x77, 0x11, 0xac, 0xf4,
	0x90, 0xa2, 0x0f, 0xac, 0xf4, 0xd0, 0x15, 0xf8, 0xf2, 0x11, 0x99, 0xb3, 0x31, 0x22, 0xa9, 0x53,
	0xcc, 0x3d, 0x88, 0xb3, 0x58, 0x6d, 0x6d, 0x6f, 0xad, 0xf4, 0x10, 0xc6, 0x5a, 0x3e, 0x87, 0x33,
	0x8b, 0xbe, 0xeb, 0xaf, 0xf4, 0x90, 0x86, 0x73, 0xf9, 0x8c, 0xfe, 0xee, 0x93, 0xb9, 0x95, 0x1e,
	0xca, 0x60, 0x45, 0x07, 0xf9, 0x54, 0x8a, 0x1f, 0x03, 0x46, 0x87, 0x6c, 0xd7, 0x69, 0xd8, 0x91,
	0x1f, 0x90, 0x6b, 0xf1, 0x3a, 0xbb, 0x13, 0xcd, 0x53, 0x2f, 0x72, 0xea, 0x76, 0x44, 0x1b, 0x7c,
	0x94, 0x34, 0x6b, 0x6d, 0x21, 0xb9, 0x09, 0xe3, 0x36, 0x0d, 0x5a, 0x4e, 0x18, 0x3a, 0xbe, 0xc7,
	0xf7, 0xf1, 0x50, 0x75, 0x4b, 0x32, 0x4c, 0x49, 0xb6, 0xf2, 0xdd, 0x49, 0x90, 0xb5, 0x0a, 0xc8,
	0xdf, 0x87, 0x71, 0xdf, 0x43, 0x46, 0x71, 0xce, 0xae, 0xb3, 0xc9, 0xe4, 0x75, 0xad, 0xaf, 0x6e,
	0xbe, 0x44, 0xa2, 0x49, 0x1e, 0x60, 0xc9, 0x40, 0x72, 0x25, 0xce, 0xb1, 0xc6, 0x44, 0x8b, 0x7c,
	0x8a, 0x90, 0x25, 0xad, 0x62, 0x09, 0xe7, 0x44, 0x24, 0x41, 0x38, 0x7b, 0xc7, 0xc1, 0x5b, 0xf7,
	0xdf, 0xa5, 0x0f, 0x10, 0x0d, 0x67, 0xac, 0xe9, 0xc9, 0x5b, 0x74, 0x60, 0x85, 0xf7, 0x59, 0xfb,
	0xef, 0x9d, 0xd6, 0x95, 0xe2, 0x39, 0x15, 0x67, 0xac, 0x8e, 0x4b, 0x49, 0x15, 0xe7, 0xc2, 0x28,
	0x70, 0xbc, 0x39, 0xb9, 0x1e, 0x8c, 0xa4, 0x76, 0xe6, 0x2e, 0xdf, 0xc3, 0x7d, 0xec, 0xf5, 0xb6,
	0x01, 0x4b, 0x46, 0x92, 0xeb, 0xb1, 0x16, 0xd0, 0x36, 0xe5, 0xe3, 0xa3, 0x70, 0x2a, 0xbf, 0x96,
	0xb2, 0xa4, 0x57, 0x72, 0x49, 0x34, 0xd9, 0x81, 0x55, 0xc7, 0x8b, 0xe4, 0x39, 0x77, 0xc5, 0x5a,
	0x68, 0xbf, 0x17, 0xc9, 0x78, 0x16, 0x93, 0x5f, 0xc4, 0xb8, 0x5f, 0x39, 0x31, 0xf0, 0x60, 0xdb,
	0x8e, 0x22, 0x1a, 0x78, 0xf2, 0x00, 0x8a, 0x4d, 0xb2, 0x15, 0x0f, 0xd9, 0xae, 0xeb, 0x3f, 0x3e,
	0x4b, 0x5b, 0x6d, 0x39, 0x20, 0x9a, 0x85, 0x79, 0xd1, 0x34, 0x2b, 0x21, 0x9b, 0xf0, 0x60, 0xcb,
	0xf1, 0x66, 0x5d, 0xea, 0xf1, 0x7a, 0xb3, 0x56, 0xae, 0xe5, 0x78, 0x77, 0x50, 0x8f, 0x3b, 0xec,
	0x05, 0xee, 0xc8, 0x48, 0x87, 0xbd, 0x70, 0x07, 0xf5, 0xf2, 0xbb, 0xf1, 0xa0, 0x6c, 0x4c, 0x0c,
	0x1f, 0xb6, 0x5d, 0x5e, 0xaf, 0xca, 0xe1, 0x43, 0xb6, 0x1b, 0xc3, 0xcc, 0x21, 0xce, 0x7d, 0x06,
	0x1f, 0xb2, 0xdd, 0xfc, 0x77, 0x01, 0x0f, 0xaf, 0xee, 0xff, 0x85, 0x0d, 0x84, 0x8b, 0x1a, 0x78,
	0x15, 0x46, 0xac, 0x0e, 0x27, 0xa2, 0xad, 0x50, 0x1e, 0xa5, 0x5a, 0xcb, 0xf1, 0xf6, 0x33, 0x9b,
	0x3b, 0xed, 0x05, 0xe9, 0x54, 0xa5, 0xd3, 0x5e, 0x10, 0xce, 0x6b, 0x70, 0x56, 0x38, 0x32, 0x17,
	0xec, 0x65, 0x56, 0xb1, 0x25, 0x7c, 0x53, 0x39, 0x9c, 0x09, 0x3a, 0x2e, 0x2d, 0xb6, 0xf0, 0x86,
	0xfd, 0xe1, 0x64, 0x27, 0x9a, 0xf7, 0x03, 0xe7, 0x08, 0x6d, 0x58, 0xf4, 0x31, 0xf2, 0x00, 0xd6,
	0xc2, 0x4e, 0xed, 0x11, 0x5a, 0x8f, 0x42, 0x03, 0x0a, 0x6a, 0x09, 0x4d, 0xdd, 0x7c, 0xfc, 0xce,
	0xdd, 0xe4, 0x06, 0x1d, 0x8a, 0xbb, 0xf0, 0x18, 0x1e, 0xfd, 0x46, 0x69, 0x8f, 0x59, 0xda, 0x63,
	0x46, 0xd4, 0x6e, 0xb1, 0xa7, 0xeb, 0xd7, 0x6d, 0xf7, 0xa8, 0xdb, 0xb0, 0xdb, 0x3b, 0x76, 0x1c,
	0xed, 0x84, 0x34, 0xd8, 0x61, 0x3e, 0xf8, 0xa0, 0x69, 0xbb, 0x5e, 0xa7, 0x65, 0x3e, 0x34, 0xfb,
	0xe5, 0x87, 0xbe, 0x78, 0xad, 0x95, 0xe4, 0x2b, 0x7e, 0x98, 0xc3, 0x97, 0xdd, 0x4e, 0x17, 0x1f,
	0xf7, 0x83, 0xc6, 0x3e, 0xdf, 0x75, 0x1d, 0xb6, 0xd6, 0x43, 0xb6, 0x72, 0xc3, 0x45, 0x2f, 0xb2,
	0x17, 0xe4, 0x38, 0x48, 0x8b, 0x95, 0x3b, 0xad, 0xb6, 0x1f, 0x44, 0x72, 0x02, 0xa5, 0xc5, 0xca,
	0xdb, 0x9d, 0x9a, 0xeb, 0xd4, 0x79, 0xdf, 0x35, 0x4b, 0x5a, 0xec, 0x16, 0x7e, 0x9c, 0xda, 0x8f,
	0xf2, 0x8e, 0x6b, 0x16, 0x7f, 0x17, 0x6b, 0xa4, 0xfe, 0xa8, 0x3d, 0x47, 0x8d, 0x2c, 0x2f, 0x8e,
	0x4d, 0x5e, 0xab, 0x58, 0xe4, 0x39, 0xb1, 0x5f, 0xe4, 0x42, 0xde, 0x88, 0xb3, 0xb5, 0xc5, 0x88,
	0x86, 0xc6, 0x20, 0xbb, 0x16, 0x2d, 0x61, 0xb0, 0x52, 0xc7, 0x8b, 0xc6, 0xaa, 0x86, 0x26, 0xae,
	0x35, 0x6e, 0xc8, 0xd2, 0x89, 0x71, 0x03, 0xf1, 0x75, 0x20, 0x0c, 0x96, 0xb9, 0x23, 0x82, 0x71,
	0x01, 0x4a, 0xeb, 0x2c, 0x69, 0xc5, 0xe5, 0x13, 0xe3, 0xc6, 0x90, 0x58, 0x1d, 0x9d, 0x24, 0x3e,
	0x14, 0xf1, 0xc3, 0x05, 0x28, 0x5d, 0x66, 0x49, 0x2b, 0x2e, 0x9f, 0x18, 0x37, 0xd6, 0x15, 0xa0,
	0x44, 0x2c, 0x69, 0xb1, 0x3e, 0x35, 0x9d, 0x05, 0xda, 0x18, 0xab, 0x1a, 0xeb, 0x0b, 0x50, 0x1a,
	0xb4, 0x62, 0x33, 0xf1, 0x4c, 0x8c, 0x1b, 0x1b, 0x0a, 0x50, 0xca, 0x59, 0xb1, 0x49, 0xf2, 0x58,
	0x0b, 0x63, 0x48, 0x2f, 0x40, 0x69, 0x83, 0x95, 0xd8, 0x7d, 0xdf, 0xc4, 0xb8, 0x71, 0x59, 0x01,
	0x4a, 0xba, 0x95, 0xd8, 0x6c, 0x4c, 0x6b, 0xbe, 0xef, 0x1a, 0x44, 0x8c, 0x29, 0x7b, 0x67, 0xbd,
	0x6e, 0xba, 0xbe, 0x1d, 0x19, 0x97, 0x17, 0xa0, 0xa4, 0x58, 0xc2, 0x60, 0xad, 0x6d, 0xf8, 0x9d,
	0x9a, 0x4b, 0x8d, 0x8d, 0x05, 0x28, 0x81, 0x25, 0x2d, 0x96, 0xdd, 0xe7, 0xd7, 0x9d, 0xed, 0x1a,
	0x57, 0xf0, 0x2c, 0x89, 0xcd, 0x7c, 0xc9, 0xa1, 0x71, 0xa5, 0xf0, 0x25, 0xc7, 0x02, 0xf7, 0x3d,
	0xd6, 0x71, 0x02, 0xda, 0x30, 0x36, 0xc5, 0x3e, 0x61, 0xb3, 0x7e, 0xb6, 0xc4, 0xdd, 0x67, 0x18,
	0x62, 0x56, 0xa5, 0xc9, 0xda, 0x4b, 0xbd, 0x4e, 0xcb, 0xd8, 0x2c, 0xda, 0xcb, 0xde, 0x59, 0x34,
	0xbb, 0x1c, 0x9d, 0x3a, 0x35, 0xf2, 0x22, 0x5a, 0x9a, 0x4c, 0xbe, 0x04, 0xed, 0xba, 0x71, 0x15,
	0x2f, 0x65, 0xaf, 0xac, 0x17, 0xa2, 0x75, 0xc6, 0x17, 0xc4, 0xda, 0x12, 0x16, 0x3f, 0x5d, 0x17,
	0x22, 0xea, 0x35, 0x8c, 0x2d, 0xa2, 0x5c, 0x58, 0xe4, 0x6a, 0x8c, 0xf9, 0x1b, 0x5f, 0xc9, 0xc6,
	0xd5, 0x62, 0x1f, 0xf7, 0x4b, 0x44, 0x2f, 0x58, 0x75, 0xb4, 0x61, 0x6c, 0x8d, 0x7b, 0x21, 0x6c,
	0xa6, 0x10, 0x23, 0xdf, 0x28, 0xf0, 0x52, 0x25, 0xf2, 0x59, 0xdb, 0xa3, 0xa0, 0x43, 0x8d, 0x6d,
	0x7c, 0x89, 0xf1, 0x77, 0x3e, 0xd6, 0xb6, 0x1b, 0x52, 0xa3, 0x28, 0xd6, 0x1d, 0x37, 0x58, 0x8f,
	0x1a, 0xb4, 0x69, 0x77, 0xdc, 0xc8, 0xb8, 0x46, 0x08, 0x08, 0x69, 0x16, 0x7f, 0xa8, 0xe2, 0x4d,
	0x17, 0xee, 0x30, 0xa9, 0x36, 0xc8, 0x7b, 0xc0, 0x25, 0x29, 0xdb, 0x64, 0x99, 0xa9, 0xb7, 0xe0,
	0xe9, 0x2e, 0x82, 0x63, 0x5d, 0x04, 0x27, 0xba, 0x08, 0x9e, 0xed, 0x22, 0x78, 0xb1, 0x8b, 0xe0,
	0xb5, 0x2e, 0x92, 0xfb, 0xe0, 0xcd, 0x2e, 0x12, 0x4b, 0xff, 0x64, 0x17, 0x15, 0x4e, 0x75, 0xd1,
	0xde, 0xd3, 0x5d, 0xb4, 0xb4, 0xf9, 0xfd, 0x2e, 0x5a, 0xaa, 0x7e, 0xd4, 0x45, 0x7b, 0xce, 0x76,
	0xd1, 0x13, 0x9f, 0x74, 0xd1, 0xb3, 0xc3, 0x03, 0x03, 0x9f, 0x75, 0xd1, 0xde, 0xcd, 0x03, 0xfc,
	0xf3, 0xed, 0x1e, 0x7a, 0xf8, 0xe3, 0xf3, 0xe7, 0xbf, 0xd3, 0x43, 0x27, 0xff, 0x71, 0x9e, 0x7f,
	0x8e, 0xf5, 0x10, 0x3c, 0xd3, 0x43, 0x6f, 0x7f, 0x72, 0xdb, 0xde, 0xe7, 0x7a, 0xc8, 0x7b, 0xea,
	0xaa, 0x73, 0x9f, 0x6d, 0x43, 0x7b, 0x5f, 0xec, 0x21, 0x78, 0xb5, 0x87, 0xe0, 0xf5, 0x1e, 0x82,
	0x93, 0x3d, 0x04, 0xa7, 0x7a, 0x08, 0x4e, 0xf7, 0x10, 0xbc, 0xdf, 0x43, 0xf0, 0x51, 0x0f, 0xc1,
	0xd9, 0x1e, 0x82, 0x73, 0x3d, 0x04, 0x9f, 0xf6, 0x10, 0x2c, 0x9d, 0x41, 0xf0, 0xf4, 0x19, 0xe4,
	0x1f, 0x3b, 0x83, 0xbe, 0x7f, 0x5e, 0x7e, 0xe0, 0xc4, 0x19, 0xf4, 0x01, 0x30, 0x59, 0x4d, 0x5e,
	0x02, 0xa9, 0xbd, 0xf9, 0xad, 0x37, 0xf5, 0x03, 0x58, 0x39, 0x83, 0xbe, 0x07, 0x1a, 0xe8, 0xc0,
	0x3b, 0x0a, 0x55, 0xd9, 0x1f, 0x53, 0xf4, 0x66, 0x6f, 0xe1, 0xb6, 0xbd, 0x77, 0x2f, 0x6d, 0xbe,
	0x7f, 0xa9, 0xfa, 0xf0, 0x9e, 0xf9, 0x27, 0x3a, 0xac, 0xfd, 0x8b, 0x49, 0xeb, 0x81, 0x37, 0x1e,
	0x92, 0xb6, 0x03, 0x3c, 0x03, 0xbc, 0xe5, 0x90, 0x34, 0x1c, 0xe0, 0x55, 0x80, 0xd7, 0x01, 0x4e,
	0x02, 0x9c, 0x02, 0x38, 0x0d, 0xf0, 0x3e, 0xc0, 0x47, 0x00, 0x67, 0x01, 0xce, 0x01, 0x7c, 0x0a,
	0xb0, 0xa4, 0xc0, 0xd3, 0x8a, 0x7f, 0x4c, 0x59, 0xd5, 0x54, 0xe5, 0x03, 0x10, 0x5f, 0x09, 0x46,
	0x16, 0xf0, 0xc6, 0x69, 0xaf, 0xd3, 0xba, 0x50, 0xaf, 0x91, 0x2c, 0x86, 0xfb, 0x75, 0x85, 0x3d,
	0xbe, 0xae, 0xab, 0xec, 0xf1, 0x80, 0x9e, 0x29, 0x72, 0xc9, 0xc6, 0x32, 0x0c, 0x16, 0xd7, 0x69,
	0xff, 0x49, 0xd2, 0xe9, 0x50, 0x64, 0xf2, 0x0e, 0x17, 0x99, 0xbc, 0xdb, 0x50, 0x64, 0xf2, 0x8e,
	0x14, 0xaf, 0xd4, 0xfe, 0xd5, 0x0f, 0xf8, 0x77, 0xf2, 0x3a, 0x02, 0xfb, 0x46, 0x60, 0x6a, 0x04,
	0x26, 0xab, 0x4f, 0x01, 0xde, 0xc0, 0x94, 0x1a, 0xfb, 0xbb, 0x47, 0x2e, 0xfe, 0x1b, 0xb1, 0xf6,
	0xb5, 0x90, 0x06, 0xec, 0xf4, 0xbf, 0x40, 0xe8, 0xe6, 0xd7, 0x9a, 0x45, 0xf2, 0xce, 0x93, 0xb9,
	0xf5, 0x1a, 0x10, 0xac, 0x0d, 0x90, 0x5c, 0xdd, 0x75, 0xa8, 0x17, 0x91, 0x5d, 0x58, 0xbd, 0x95,
	0x46, 0x29, 0xa0, 0xfe, 0xce, 0x93, 0xb9, 0x61, 0x0d, 0x88, 0xa6, 0x01, 0xc9, 0xb0, 0xcb, 0xc1,
	0xbc, 0x19, 0x67, 0x5d, 0xbb, 0x46, 0x5d, 0xb2, 0xfd, 0x22, 0x6d, 0x3c, 0x1d, 0xef, 0x1a, 0xcb,
	0xf6, 0xfa, 0x12, 0xf9, 0xd9, 0x65, 0xf9, 0x45, 0x89, 0x63, 0xe6, 0x2d, 0x38, 0x13, 0xd0, 0x76,
	0x94, 0x2e, 0xad, 0x57, 0x96, 0x81, 0x4b, 0xb0, 0x0b, 0xb5, 0x2c, 0xa3, 0xcd, 0x07, 0xb1, 0x4a,
	0x29, 0x4d, 0x4f, 0xf2, 0xd3, 0x65, 0xf8, 0x7f, 0xe4, 0xae, 0xc5, 0xb2, 0x9a, 0x93, 0x18, 0xec,
	0xf4, 0xd4, 0xbf, 0x5e, 0x16, 0xda, 0x4a, 0x4f, 0x52, 0x4b, 0x2d, 0x6e, 0x81, 0x6d, 0x7e, 0x15,
	0xa3, 0xc3, 0x89, 0xfc, 0xbc, 0xfa, 0x12, 0xa9, 0xa2, 0x79, 0xbf, 0x11, 0x67, 0x7a, 0xe3, 0x61,
	0x9e, 0x88, 0x5c, 0x2c, 0x11, 0xad, 0x7e, 0x16, 0x73, 0x1f, 0xce, 0xb2, 0x1b, 0x3f, 0x24, 0x5b,
	0x2e, 0x4a, 0xf7, 0x15, 0x87, 0xba, 0x49, 0xb6, 0xf7, 0xd0, 0x25, 0x65, 0x03, 0x67, 0xcd, 0xeb,
	0xe2, 0x9b, 0x3a, 0x2d, 0xcb, 0x73, 0xcb, 0x6b, 0xae, 0x72, 0x06, 0xca, 0xcb, 0x3b, 0x05, 0x5c,
	0x89, 0x41, 0x11, 0xce, 0x40, 0x79, 0xbb, 0xa7, 0x80, 0xcf, 0xc7, 0xa0, 0x08, 0x37, 0xc7, 0x84,
	0x18, 0x48, 0xc3, 0x7e, 0x24, 0x31, 0x1e, 0x6c, 0xde, 0x90, 0xa8, 0x85, 0x34, 0xee, 0xc7, 0x92,
	0x8b, 0xe3, 0xf9, 0xd0, 0x08, 0x01, 0x91, 0x42, 0xfe, 0x44, 0x2e, 0xe8, 0xf8, 0x5c, 0xda, 0x25,
	0xf5, 0x46, 0x1a, 0xf7, 0x02, 0xe7, 0x62, 0x41, 0xc2, 0x30, 0xa1, 0x12, 0x52, 0xb0, 0x17, 0xe5,
	0x57, 0x4c, 0x11, 0x2d, 0xb1, 0x89, 0xf1, 0x34, 0xec, 0xa5, 0x65, 0x58, 0x25, 0x69, 0x58, 0xef,
	0x3a, 0x9f, 0xab, 0x3a, 0xb1, 0x63, 0x12, 0xcd, 0x13, 0x83, 0xe9, 0x15, 0xbe, 0xcc, 0xc1, 0x44,
	0x14, 0xf1, 0xf1, 0xfc, 0x5c, 0x35, 0xbe, 0xc2, 0xc1, 0x44, 0x35, 0xc5, 0x60, 0x7a, 0x8d, 0x3f,
	0xe3, 0x60, 0x22, 0xab, 0xd8, 0xe4, 0xc7, 0x8a, 0x28, 0x85, 0xfc, 0x39, 0x27, 0xfb, 0xba, 0x2b,
	0x41, 0xd3, 0x2b, 0xfd, 0x05, 0x47, 0xfb, 0xc2, 0xcc, 0xdc, 0xdd, 0x17, 0x66, 0x69, 0xec, 0xab,
	0x9c, 0x5d, 0xa5, 0xdc, 0xfa, 0x70, 0x7a, 0xc5, 0xbf, 0xe4, 0xf0, 0x2a, 0x69, 0xc7, 0x76, 0x08,
	0x97, 0x73, 0x29, 0xe0, 0x6b, 0xf1, 0x0e, 0x61, 0xc1, 0x6c, 0xfd, 0x08, 0xb9, 0x97, 0x42, 0xfd,
	0x8a, 0x53, 0xb1, 0x38, 0x64, 0x93, 0x22, 0xe5, 0x60, 0x0a, 0x27, 0x8e, 0xc5, 0x44, 0x3d, 0xb2,
	0x1e, 0x26, 0x6a, 0x31, 0x05, 0xfd, 0x8d, 0x6c, 0x68, 0x02, 0x30, 0x38, 0x91, 0x93, 0x29, 0xf0,
	0x6f, 0x63, 0x38, 0x06, 0x04, 0x2c, 0xf5, 0x66, 0x0a, 0xfc, 0xbb, 0x3e, 0x2c, 0x00, 0xb6, 0x20,
	0x62, 0x45, 0x9a, 0xc2, 0xbe, 0x1e, 0x1f, 0x24, 0x32, 0x9e, 0x4d, 0x0b, 0x57, 0xad, 0x29, 0xdc,
	0x1b, 0xf1, 0xb4, 0xb0, 0x60, 0x56, 0x5f, 0xac, 0x69, 0x53, 0xb8, 0x37, 0xe3, 0xfa, 0x64, 0xbc,
	0x39, 0xca, 0x35, 0x70, 0x1a, 0xf6, 0x7b, 0x89, 0xb1, 0x58, 0x36, 0x9b, 0x52, 0x16, 0xa7, 0x50,
	0x7f, 0x88, 0x0f, 0x65, 0x11, 0xce, 0x40, 0xa9, 0x9b, 0x53, 0xc0, 0x3f, 0xc6, 0xa0, 0x08, 0x37,
	0xf7, 0xac, 0x96, 0xd9, 0x69, 0xf0, 0x9f, 0x24, 0xbc, 0x0a, 0x11, 0xb3, 0x29, 0x75, 0x77, 0x0a,
	0xfe, 0xe7, 0xfe, 0x6c, 0x0a, 0xc0, 0xdc, 0xc9, 0x84, 0x7a, 0x1a, 0x76, 0x52, 0x62, 0x4a, 0xe4,
	0xb3, 0x39, 0xe4, 0xea, 0x3d, 0x05, 0x79, 0x4b, 0x9e, 0xcd, 0x3c, 0x98, 0x6f, 0x2d, 0xae, 0xee,
	0x53, 0xa8, 0xbf, 0xc4, 0x27, 0x3a, 0x8f, 0x66, 0x53, 0x2f, 0xc5, 0x7f, 0x1a, 0xf8, 0x76, 0xfc,
	0x6b, 0xa3, 0x8c, 0x37, 0x0f, 0xf2, 0x13, 0x20, 0x75, 0xa9, 0xfd, 0x55, 0x4a, 0x95, 0xfe, 0x0f,
	0x3a, 0x17, 0x7d, 0x87, 0xe7, 0xa7, 0x43, 0x6b, 0x6a, 0xec, 0x81, 0xd1, 0x39, 0x27, 0x9a, 0xef,
	0xd4, 0xca, 0x75, 0xbf, 0xb5, 0xf3, 0x91, 0xf9, 0x4e, 0xab, 0x2d, 0x7e, 0x3f, 0x0f, 0x68, 0xd3,
	0xa5, 0xf5, 0x68, 0xa7, 0xe3, 0x45, 0x34, 0xf0, 0x6c, 0x77, 0x67, 0x44, 0xc3, 0x88, 0x7b, 0xc2,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x3a, 0xf4, 0x5b, 0x8b, 0x17, 0x00, 0x00,
}
