// This is the first detached comment for the syntax.

//
// This is a second detached comment.

// This is a third.

// Syntax comment...

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.1
// source: desc_test_comments.proto

// And now the package declaration

package testprotos

import (
	sync "sync"
	unsafe "unsafe"

	reflect "github.com/goccy/go-reflect"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of google/protobuf/empty.proto.

type Empty = emptypb.Empty

type Request_MarioCharacters int32

const (
	Request_MARIO     Request_MarioCharacters = 1
	Request_LUIGI     Request_MarioCharacters = 2
	Request_PEACH     Request_MarioCharacters = 3
	Request_BOWSER    Request_MarioCharacters = 4
	Request_WARIO     Request_MarioCharacters = 5
	Request_WALUIGI   Request_MarioCharacters = 6
	Request_SHY_GUY   Request_MarioCharacters = 7
	Request_HEY_HO    Request_MarioCharacters = 7
	Request_MAGIKOOPA Request_MarioCharacters = 8
	Request_KAMEK     Request_MarioCharacters = 8
	Request_SNIFIT    Request_MarioCharacters = -101
)

// Enum value maps for Request_MarioCharacters.
var (
	Request_MarioCharacters_name = map[int32]string{
		1: "MARIO",
		2: "LUIGI",
		3: "PEACH",
		4: "BOWSER",
		5: "WARIO",
		6: "WALUIGI",
		7: "SHY_GUY",
		// Duplicate value: 7: "HEY_HO",
		8: "MAGIKOOPA",
		// Duplicate value: 8: "KAMEK",
		-101: "SNIFIT",
	}
	Request_MarioCharacters_value = map[string]int32{
		"MARIO":     1,
		"LUIGI":     2,
		"PEACH":     3,
		"BOWSER":    4,
		"WARIO":     5,
		"WALUIGI":   6,
		"SHY_GUY":   7,
		"HEY_HO":    7,
		"MAGIKOOPA": 8,
		"KAMEK":     8,
		"SNIFIT":    -101,
	}
)

func (x Request_MarioCharacters) Enum() *Request_MarioCharacters {
	p := new(Request_MarioCharacters)
	*p = x
	return p
}

func (x Request_MarioCharacters) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_MarioCharacters) Descriptor() protoreflect.EnumDescriptor {
	return file_desc_test_comments_proto_enumTypes[0].Descriptor()
}

func (Request_MarioCharacters) Type() protoreflect.EnumType {
	return &file_desc_test_comments_proto_enumTypes[0]
}

func (x Request_MarioCharacters) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Request_MarioCharacters) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Request_MarioCharacters(num)
	return nil
}

// Deprecated: Use Request_MarioCharacters.Descriptor instead.
func (Request_MarioCharacters) EnumDescriptor() ([]byte, []int) {
	return file_desc_test_comments_proto_rawDescGZIP(), []int{0, 0}
}

// We need a request for our RPC service below.
//
// Deprecated: Marked as deprecated in desc_test_comments.proto.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A field comment
	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids,json=|foo|" json:"ids,omitempty"` // field trailer #1...
	// label comment
	Name   *string         `protobuf:"bytes,2,opt,name=name,def=fubar" json:"name,omitempty"`
	Extras *Request_Extras `protobuf:"group,3,opt,name=Extras,json=extras" json:"extras,omitempty"`
	// can be this or that
	//
	// Types that are valid to be assigned to Abc:
	//
	//	*Request_This
	//	*Request_That
	Abc isRequest_Abc `protobuf_oneof:"abc"`
	// can be these or those
	//
	// Types that are valid to be assigned to Xyz:
	//
	//	*Request_These
	//	*Request_Those
	Xyz isRequest_Xyz `protobuf_oneof:"xyz"`
	// map field
	Things          map[string]string `protobuf:"bytes,8,rep,name=things" json:"things,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	extensionFields protoimpl.ExtensionFields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Default values for Request fields.
const (
	Default_Request_Name = string("fubar")
)

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_desc_test_comments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_desc_test_comments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_desc_test_comments_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *Request) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return Default_Request_Name
}

func (x *Request) GetExtras() *Request_Extras {
	if x != nil {
		return x.Extras
	}
	return nil
}

func (x *Request) GetAbc() isRequest_Abc {
	if x != nil {
		return x.Abc
	}
	return nil
}

func (x *Request) GetThis() string {
	if x != nil {
		if x, ok := x.Abc.(*Request_This); ok {
			return x.This
		}
	}
	return ""
}

func (x *Request) GetThat() int32 {
	if x != nil {
		if x, ok := x.Abc.(*Request_That); ok {
			return x.That
		}
	}
	return 0
}

func (x *Request) GetXyz() isRequest_Xyz {
	if x != nil {
		return x.Xyz
	}
	return nil
}

func (x *Request) GetThese() string {
	if x != nil {
		if x, ok := x.Xyz.(*Request_These); ok {
			return x.These
		}
	}
	return ""
}

func (x *Request) GetThose() int32 {
	if x != nil {
		if x, ok := x.Xyz.(*Request_Those); ok {
			return x.Those
		}
	}
	return 0
}

func (x *Request) GetThings() map[string]string {
	if x != nil {
		return x.Things
	}
	return nil
}

type isRequest_Abc interface {
	isRequest_Abc()
}

type Request_This struct {
	This string `protobuf:"bytes,4,opt,name=this,oneof"`
}

type Request_That struct {
	That int32 `protobuf:"varint,5,opt,name=that,oneof"`
}

func (*Request_This) isRequest_Abc() {}

func (*Request_That) isRequest_Abc() {}

type isRequest_Xyz interface {
	isRequest_Xyz()
}

type Request_These struct {
	These string `protobuf:"bytes,6,opt,name=these,oneof"`
}

type Request_Those struct {
	Those int32 `protobuf:"varint,7,opt,name=those,oneof"`
}

func (*Request_These) isRequest_Xyz() {}

func (*Request_Those) isRequest_Xyz() {}

type AnEmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnEmptyMessage) Reset() {
	*x = AnEmptyMessage{}
	mi := &file_desc_test_comments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnEmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnEmptyMessage) ProtoMessage() {}

func (x *AnEmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_desc_test_comments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnEmptyMessage.ProtoReflect.Descriptor instead.
func (*AnEmptyMessage) Descriptor() ([]byte, []int) {
	return file_desc_test_comments_proto_rawDescGZIP(), []int{1}
}

// Group comment with emoji 😀 😍 👻 ❤ 💯 💥 🐶 🦂 🥑 🍻 🌍 🚕 🪐
type Request_Extras struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Dbl   *float64               `protobuf:"fixed64,1,opt,name=dbl" json:"dbl,omitempty"`
	Flt   *float32               `protobuf:"fixed32,2,opt,name=flt" json:"flt,omitempty"`
	// Leading comment...
	Str           *string `protobuf:"bytes,3,opt,name=str" json:"str,omitempty"` // Trailing comment...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_Extras) Reset() {
	*x = Request_Extras{}
	mi := &file_desc_test_comments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_Extras) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Extras) ProtoMessage() {}

func (x *Request_Extras) ProtoReflect() protoreflect.Message {
	mi := &file_desc_test_comments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Extras.ProtoReflect.Descriptor instead.
func (*Request_Extras) Descriptor() ([]byte, []int) {
	return file_desc_test_comments_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_Extras) GetDbl() float64 {
	if x != nil && x.Dbl != nil {
		return *x.Dbl
	}
	return 0
}

func (x *Request_Extras) GetFlt() float32 {
	if x != nil && x.Flt != nil {
		return *x.Flt
	}
	return 0
}

func (x *Request_Extras) GetStr() string {
	if x != nil && x.Str != nil {
		return *x.Str
	}
	return ""
}

var file_desc_test_comments_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*Request)(nil),
		ExtensionType: (*uint64)(nil),
		Field:         123,
		Name:          "foo.bar.guid1",
		Tag:           "varint,123,opt,name=guid1",
		Filename:      "desc_test_comments.proto",
	},
	{
		ExtendedType:  (*Request)(nil),
		ExtensionType: (*uint64)(nil),
		Field:         124,
		Name:          "foo.bar.guid2",
		Tag:           "varint,124,opt,name=guid2",
		Filename:      "desc_test_comments.proto",
	},
}

// Extension fields to Request.
var (
	// comment for guid1
	//
	// optional uint64 guid1 = 123;
	E_Guid1 = &file_desc_test_comments_proto_extTypes[0]
	// ... and a comment for guid2
	//
	// optional uint64 guid2 = 124;
	E_Guid2 = &file_desc_test_comments_proto_extTypes[1]
)

var File_desc_test_comments_proto protoreflect.FileDescriptor

const file_desc_test_comments_proto_rawDesc = "" +
	"\n" +
	"\x18desc_test_comments.proto\x12\afoo.bar\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17desc_test_options.proto\"\xe8\x05\n" +
	"\aRequest\x12$\n" +
	"\x03ids\x18\x01 \x03(\x05B\x10\xaa\xf7\x04\x03abc\xb2\xf7\x04\x03xyz\x10\x01R\x05|foo|\x12\x19\n" +
	"\x04name\x18\x02 \x01(\t:\x05fubarR\x04name\x12/\n" +
	"\x06extras\x18\x03 \x01(\n" +
	"2\x17.foo.bar.Request.ExtrasR\x06extras\x12\x14\n" +
	"\x04this\x18\x04 \x01(\tH\x00R\x04this\x12\x14\n" +
	"\x04that\x18\x05 \x01(\x05H\x00R\x04that\x12\x16\n" +
	"\x05these\x18\x06 \x01(\tH\x01R\x05these\x12\x16\n" +
	"\x05those\x18\a \x01(\x05H\x01R\x05those\x124\n" +
	"\x06things\x18\b \x03(\v2\x1c.foo.bar.Request.ThingsEntryR\x06things\x1aF\n" +
	"\x06Extras\x12\x10\n" +
	"\x03dbl\x18\x01 \x01(\x01R\x03dbl\x12\x10\n" +
	"\x03flt\x18\x02 \x01(\x02R\x03flt\x12\x10\n" +
	"\x03str\x18\x03 \x01(\tR\x03str:\x06\xa8\xf7\x04\x00\x10\x00\x1a9\n" +
	"\vThingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\x0fMarioCharacters\x12\x15\n" +
	"\x05MARIO\x10\x01\x1a\n" +
	"\xa8\xf7\x04\x96\x02\xb0\xf7\x04\xf3\x04\x12\x1b\n" +
	"\x05LUIGI\x10\x02\x1a\x10\xc0\xf7\x04\xc8\x01\xc9\xf7\x04d\x00\x00\x00\x00\x00\x00\x00\x12\t\n" +
	"\x05PEACH\x10\x03\x12\n" +
	"\n" +
	"\x06BOWSER\x10\x04\x12\t\n" +
	"\x05WARIO\x10\x05\x12\v\n" +
	"\aWALUIGI\x10\x06\x12\x18\n" +
	"\aSHY_GUY\x10\a\x1a\v\xb9\xf7\x04u'\x00\x00\x00\x00\x00\x00\x12\n" +
	"\n" +
	"\x06HEY_HO\x10\a\x12\r\n" +
	"\tMAGIKOOPA\x10\b\x12\t\n" +
	"\x05KAMEK\x10\b\x12\x13\n" +
	"\x06SNIFIT\x10\x9b\xff\xff\xff\xff\xff\xff\xff\xff\x01\x1a\v\xa8\xf7\x04{\xb0\xf7\x04\x81\x05\x10\x01*\x05\bd\x10\xc9\x01*\x1e\b\xc9\x01\x10\xfb\x01\x1a\x16\xaa\xf7\x04\x06splat!\xb2\xf7\x04\b\x00\x01\x02\x03\x04\x05\x06\a:\x06\xa8\xf7\x04\x01\x18\x01B\x05\n" +
	"\x03abcB,\n" +
	"\x03xyz\x12%\xaa\xf7\x04!whoops, this has invalid UTF8! \xbc\xffJ\x04\b\n" +
	"\x10\x15J\x04\b\x1e\x103R\x03fooR\x03barR\x03baz\"\x10\n" +
	"\x0eAnEmptyMessage2\xa3\x01\n" +
	"\n" +
	"RpcService\x124\n" +
	"\fStreamingRpc\x12\x10.foo.bar.Request\x1a\x10.foo.bar.Request(\x01\x12K\n" +
	"\bUnaryRpc\x12\x10.foo.bar.Request\x1a\x16.google.protobuf.Empty\"\x15\xad\xf7\x04\xa4pEA\xb1\xf7\x04w\xbe\x9f\x1a/\xdd^@\x88\x02\x01\x1a\x12\xaa\xf7\x04\a\bd\x12\x03bob\xb0\xf7\x04\x01\x88\x02\x00:&\n" +
	"\x05guid1\x12\x10.foo.bar.Request\x18{ \x01(\x04R\x05guid1:&\n" +
	"\x05guid2\x12\x10.foo.bar.Request\x18| \x01(\x04R\x05guid2B6Z4github.com/jhump/protoreflect/v2/internal/testprotosP\x00"

var (
	file_desc_test_comments_proto_rawDescOnce sync.Once
	file_desc_test_comments_proto_rawDescData []byte
)

func file_desc_test_comments_proto_rawDescGZIP() []byte {
	file_desc_test_comments_proto_rawDescOnce.Do(func() {
		file_desc_test_comments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_test_comments_proto_rawDesc), len(file_desc_test_comments_proto_rawDesc)))
	})
	return file_desc_test_comments_proto_rawDescData
}

var file_desc_test_comments_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_desc_test_comments_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_desc_test_comments_proto_goTypes = []any{
	(Request_MarioCharacters)(0), // 0: foo.bar.Request.MarioCharacters
	(*Request)(nil),              // 1: foo.bar.Request
	(*AnEmptyMessage)(nil),       // 2: foo.bar.AnEmptyMessage
	(*Request_Extras)(nil),       // 3: foo.bar.Request.Extras
	nil,                          // 4: foo.bar.Request.ThingsEntry
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_desc_test_comments_proto_depIdxs = []int32{
	3, // 0: foo.bar.Request.extras:type_name -> foo.bar.Request.Extras
	4, // 1: foo.bar.Request.things:type_name -> foo.bar.Request.ThingsEntry
	1, // 2: foo.bar.guid1:extendee -> foo.bar.Request
	1, // 3: foo.bar.guid2:extendee -> foo.bar.Request
	1, // 4: foo.bar.RpcService.StreamingRpc:input_type -> foo.bar.Request
	1, // 5: foo.bar.RpcService.UnaryRpc:input_type -> foo.bar.Request
	1, // 6: foo.bar.RpcService.StreamingRpc:output_type -> foo.bar.Request
	5, // 7: foo.bar.RpcService.UnaryRpc:output_type -> google.protobuf.Empty
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	2, // [2:4] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_desc_test_comments_proto_init() }
func file_desc_test_comments_proto_init() {
	if File_desc_test_comments_proto != nil {
		return
	}
	file_desc_test_options_proto_init()
	file_desc_test_comments_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_This)(nil),
		(*Request_That)(nil),
		(*Request_These)(nil),
		(*Request_Those)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_test_comments_proto_rawDesc), len(file_desc_test_comments_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 2,
			NumServices:   1,
		},
		GoTypes:           file_desc_test_comments_proto_goTypes,
		DependencyIndexes: file_desc_test_comments_proto_depIdxs,
		EnumInfos:         file_desc_test_comments_proto_enumTypes,
		MessageInfos:      file_desc_test_comments_proto_msgTypes,
		ExtensionInfos:    file_desc_test_comments_proto_extTypes,
	}.Build()
	File_desc_test_comments_proto = out.File
	file_desc_test_comments_proto_goTypes = nil
	file_desc_test_comments_proto_depIdxs = nil
}
